# Generated by Django 5.2.12 on 2026-04-02 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finanzas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivoFijo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('valor_adquisicion', models.DecimalField(decimal_places=2, max_digits=14)),
                ('vida_util_meses', models.PositiveIntegerField(default=60)),
                ('fecha_adquisicion', models.DateField()),
                ('depreciacion_acumulada', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('en_mantenimiento', 'En mantenimiento'), ('baja', 'Baja')], default='activo', max_length=20)),
            ],
        ),
    ]
