# Generated by Django 5.2.12 on 2026-04-02 16:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_cotizacion_forma_pago_cotizacion_garantia_and_more'),
        ('proyectos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_ps', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('en_ejecucion', 'En Ejecución'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='planificado', max_length=20)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proyectos_ps_set', to='crm.cliente')),
                ('gerente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
