# Generated by Django 5.2.12 on 2026-04-02 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyectos', '0002_proyectops'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyectops',
            name='costo_comprometido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='proyectops',
            name='costo_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='proyectops',
            name='estado',
            field=models.CharField(choices=[('planificado', 'Planificado'), ('en_ejecucion', 'En Ejecución'), ('completado', 'Completado'), ('cerrado', 'Cerrado'), ('cancelado', 'Cancelado')], default='planificado', max_length=20),
        ),
        migrations.AlterField(
            model_name='proyectops',
            name='presupuesto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.CreateModel(
            name='CostoPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('mano_obra', 'Mano de Obra'), ('materiales', 'Materiales'), ('subcontrato', 'Subcontrato'), ('otro', 'Otro')], max_length=50)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costos', to='proyectos.proyectops')),
            ],
        ),
        migrations.CreateModel(
            name='HitoPS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('fecha_programada', models.DateField()),
                ('fecha_real', models.DateField(blank=True, null=True)),
                ('progreso', models.IntegerField(default=0)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos_ps', to='proyectos.proyectops')),
            ],
        ),
        migrations.CreateModel(
            name='WBSItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_items', to='proyectos.wbsitem')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wbs_items', to='proyectos.proyectops')),
            ],
        ),
    ]
