# Generated by Django 5.2.12 on 2026-04-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFacturatech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_config', models.CharField(default='Configuración Principal', max_length=100)),
                ('nit', models.CharField(help_text='NIT sin DV', max_length=20)),
                ('password_hash', models.CharField(help_text='Contraseña hasheada en SHA256', max_length=64)),
                ('wsdl_demo_ventas', models.URLField(blank=True, help_text='WSDL Demo Ventas')),
                ('wsdl_demo_pos', models.URLField(blank=True, help_text='WSDL Demo POS')),
                ('wsdl_prod_ventas', models.URLField(blank=True, help_text='WSDL Producción Ventas')),
                ('wsdl_prod_pos', models.URLField(blank=True, help_text='WSDL Producción POS')),
                ('ambiente_activo', models.CharField(choices=[('demo', 'Demo/Pruebas'), ('produccion', 'Producción')], default='demo', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración Facturatech',
                'verbose_name_plural': 'Configuraciones Facturatech',
                'db_table': 'facturacion_electronica_config',
            },
        ),
        migrations.CreateModel(
            name='FacturaElectronicaLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura_id', models.IntegerField(blank=True, help_text='ID de factura interna', null=True)),
                ('factura_numero', models.CharField(blank=True, help_text='Número de factura', max_length=50)),
                ('xml_enviado', models.TextField(help_text='XML UBL 2.1 enviado a Facturatech')),
                ('xml_base64', models.TextField(help_text='XML codificado en Base64')),
                ('respuesta_ws', models.TextField(blank=True, help_text='Respuesta completa del Web Service')),
                ('codigo_respuesta', models.CharField(blank=True, help_text='Código HTTP de respuesta', max_length=10)),
                ('mensaje_respuesta', models.TextField(blank=True, help_text='Mensaje descriptivo de la respuesta')),
                ('cufe', models.CharField(blank=True, help_text='Código Único de Factura Electrónica', max_length=100)),
                ('track_id', models.CharField(blank=True, help_text='ID de seguimiento DIAN', max_length=100)),
                ('qr_code', models.TextField(blank=True, help_text='Datos para generación de código QR')),
                ('estado_dian', models.CharField(blank=True, help_text='Estado en la DIAN', max_length=50)),
                ('estado_interno', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada por DIAN'), ('rechazada', 'Rechazada'), ('error', 'Error de envío')], default='pendiente', help_text='Estado interno del proceso', max_length=20)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('intentos_envio', models.IntegerField(default=0, help_text='Número de intentos de envío')),
                ('error_detalle', models.TextField(blank=True, help_text='Detalle del error si falla')),
                ('error_codigo', models.CharField(blank=True, help_text='Código de error interno', max_length=20)),
                ('es_produccion', models.BooleanField(default=False, help_text='True=Producción, False=Demo')),
                ('wsdl_url', models.URLField(blank=True, help_text='URL del WSDL usado')),
            ],
            options={
                'verbose_name': 'Log de Factura Electrónica',
                'verbose_name_plural': 'Logs de Facturas Electrónicas',
                'db_table': 'facturacion_electronica_logs',
                'ordering': ['-fecha_envio'],
                'indexes': [models.Index(fields=['factura_id'], name='facturacion_factura_664dc4_idx'), models.Index(fields=['cufe'], name='facturacion_cufe_212be2_idx'), models.Index(fields=['track_id'], name='facturacion_track_i_882fa0_idx'), models.Index(fields=['estado_interno'], name='facturacion_estado__150130_idx'), models.Index(fields=['fecha_envio'], name='facturacion_fecha_e_dc7e42_idx')],
            },
        ),
    ]
