# Generated by Django 5.2.12 on 2026-05-19 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("facturacion_electronica", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="facturaelectronicalog",
            name="explicacion_ia",
            field=models.TextField(
                blank=True,
                help_text="Explicación amigable del error de la DIAN generada por IA.",
                null=True,
            ),
        ),
    ]
