# Generated by Django 5.2.12 on 2026-06-18 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interventoria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallazgo',
            name='visita',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallazgos', to='interventoria.visitainterventoria'),
        ),
    ]
