# Generated by Django 5.2.12 on 2026-06-21 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operaciones', '0003_rename_act_sst_ambiental_informediarioproy_act_ambiental_and_more'),
        ('rrhh', '0005_empleado_firma'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.IntegerField(verbose_name='Mes (1-12)')),
                ('anio', models.IntegerField(verbose_name='Año')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin')),
                ('resumen_ejecutivo', models.TextField(blank=True, verbose_name='Resumen ejecutivo')),
                ('logros_principales', models.TextField(blank=True, verbose_name='Logros principales')),
                ('dificultades', models.TextField(blank=True, verbose_name='Dificultades / Retrasos')),
                ('observaciones', models.TextField(blank=True)),
                ('estado_terreno', models.TextField(blank=True, verbose_name='Estado del terreno')),
                ('curva_s_data', models.JSONField(blank=True, default=list, verbose_name='Datos Curva S')),
                ('resumen_personal', models.JSONField(blank=True, default=dict)),
                ('resumen_maquinaria', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('aprobado', 'Aprobado')], default='borrador', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('elaborado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensuales_elaborados', to='rrhh.empleado')),
                ('profesional_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensuales_profesional_1', to='rrhh.empleado')),
                ('profesional_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensuales_profesional_2', to='rrhh.empleado')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='informes_mensuales', to='operaciones.proyecto', verbose_name='Proyecto/Obra')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensuales_revisados', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Informe Mensual',
                'verbose_name_plural': 'Informes Mensuales',
                'ordering': ['-anio', '-mes'],
                'unique_together': {('proyecto', 'mes', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='InformeSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin')),
                ('semana_numero', models.IntegerField(default=0, verbose_name='N° Semana')),
                ('resumen_ejecutivo', models.TextField(blank=True, verbose_name='Resumen ejecutivo')),
                ('logros_principales', models.TextField(blank=True, verbose_name='Logros principales')),
                ('dificultades', models.TextField(blank=True, verbose_name='Dificultades / Retrasos')),
                ('observaciones', models.TextField(blank=True)),
                ('estado_terreno', models.TextField(blank=True, verbose_name='Estado del terreno')),
                ('curva_s_data', models.JSONField(blank=True, default=list, verbose_name='Datos Curva S')),
                ('resumen_personal', models.JSONField(blank=True, default=dict)),
                ('resumen_maquinaria', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('aprobado', 'Aprobado')], default='borrador', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('elaborado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semanales_elaborados', to='rrhh.empleado')),
                ('profesional_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semanales_profesional_1', to='rrhh.empleado')),
                ('profesional_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semanales_profesional_2', to='rrhh.empleado')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='informes_semanales', to='operaciones.proyecto', verbose_name='Proyecto/Obra')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semanales_revisados', to='rrhh.empleado')),
            ],
            options={
                'verbose_name': 'Informe Semanal',
                'verbose_name_plural': 'Informes Semanales',
                'ordering': ['-fecha_inicio'],
                'unique_together': {('proyecto', 'fecha_inicio', 'fecha_fin')},
            },
        ),
    ]
