# Generated by Django 5.2.12 on 2026-05-10 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaActividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=255, unique=True)),
                ("orden", models.IntegerField(default=0)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Categoría de Actividad",
                "verbose_name_plural": "Categorías de Actividades",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="CategoriaRecurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, unique=True)),
                ("orden", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name": "Categoría de Recurso",
                "verbose_name_plural": "Categorías de Recursos",
                "ordering": ["orden", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="Obra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=50, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("ubicacion", models.CharField(blank=True, max_length=255)),
                ("cliente", models.CharField(blank=True, max_length=200)),
                ("activo", models.BooleanField(default=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Obra",
                "verbose_name_plural": "Obras",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="InformeDiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField()),
                ("dia_semana", models.CharField(blank=True, max_length=20)),
                ("numero_paginas", models.IntegerField(default=1)),
                ("codigo_formato", models.CharField(default="F-141-IN", max_length=50)),
                ("observaciones_generales", models.TextField(blank=True)),
                (
                    "estado_terreno_inicio",
                    models.TextField(
                        blank=True,
                        help_text="Estado al iniciar la jornada (riesgos físicos/locativos)",
                    ),
                ),
                (
                    "estado_terreno_final",
                    models.TextField(
                        blank=True,
                        help_text="Estado al finalizar la jornada (riesgos físicos/locativos)",
                    ),
                ),
                ("elaborado_por", models.CharField(blank=True, max_length=200)),
                ("cargo_elaborado", models.CharField(blank=True, max_length=200)),
                ("revisado_por", models.CharField(blank=True, max_length=200)),
                ("cargo_revisado", models.CharField(blank=True, max_length=200)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "obra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="informes",
                        to="informe_diario.obra",
                    ),
                ),
            ],
            options={
                "verbose_name": "Informe Diario",
                "verbose_name_plural": "Informes Diarios",
                "ordering": ["-fecha"],
                "unique_together": {("obra", "fecha")},
            },
        ),
        migrations.CreateModel(
            name="AnexoFoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.CharField(blank=True, max_length=500)),
                ("imagen", models.ImageField(upload_to="informe_diario/anexos/%Y/%m/")),
                (
                    "seccion",
                    models.CharField(
                        choices=[
                            ("actividades", "Registro Fotográfico Actividades"),
                            ("sst", "Seguridad, Salud y Medio Ambiente"),
                        ],
                        default="actividades",
                        max_length=50,
                    ),
                ),
                ("orden", models.IntegerField(default=0)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "informe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anexos",
                        to="informe_diario.informediario",
                    ),
                ),
            ],
            options={
                "ordering": ["seccion", "orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="Actividad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descripcion", models.TextField()),
                ("orden", models.IntegerField(default=0)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="informe_diario.categoriaactividad",
                    ),
                ),
                (
                    "informe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="actividades",
                        to="informe_diario.informediario",
                    ),
                ),
            ],
            options={
                "ordering": ["categoria__orden", "orden", "id"],
            },
        ),
        migrations.CreateModel(
            name="Recurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=200)),
                (
                    "unidad",
                    models.CharField(
                        default="unidad",
                        help_text="Ej: unidad, persona, hora",
                        max_length=20,
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                ("orden", models.IntegerField(default=0)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="recursos",
                        to="informe_diario.categoriarecurso",
                    ),
                ),
            ],
            options={
                "verbose_name": "Recurso",
                "verbose_name_plural": "Recursos",
                "ordering": ["categoria", "orden", "nombre"],
                "unique_together": {("categoria", "nombre")},
            },
        ),
        migrations.CreateModel(
            name="DetalleRecurso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("observacion", models.CharField(blank=True, max_length=255)),
                (
                    "informe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="informe_diario.informediario",
                    ),
                ),
                (
                    "recurso",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="informe_diario.recurso",
                    ),
                ),
            ],
            options={
                "ordering": ["recurso__categoria__orden", "recurso__orden"],
                "unique_together": {("informe", "recurso")},
            },
        ),
        migrations.CreateModel(
            name="ReporteLluvia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hora", models.IntegerField()),
                ("con_lluvia", models.BooleanField(default=False)),
                (
                    "informe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reportes_lluvia",
                        to="informe_diario.informediario",
                    ),
                ),
            ],
            options={
                "ordering": ["hora"],
                "unique_together": {("informe", "hora")},
            },
        ),
    ]
