# Generated by Django 5.2.12 on 2026-05-13 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe_diario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informediario',
            name='comision_topografia',
            field=models.BooleanField(default=False, help_text='Comisión de Topografía presente'),
        ),
    ]
