# Generated by Django 5.2.12 on 2026-05-14 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe_diario', '0002_informediario_comision_topografia'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemObra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, help_text='Número/código de ítem', max_length=50)),
                ('descripcion', models.TextField()),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('orden', models.IntegerField(default=0)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_obra', to='informe_diario.informediario')),
            ],
            options={
                'verbose_name': 'Ítem de Obra',
                'verbose_name_plural': 'Ítems de Obra',
                'ordering': ['orden', 'id'],
            },
        ),
    ]
