# Generated by Django 5.2.12 on 2026-05-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("informe_diario", "0003_add_itemobra"),
    ]

    operations = [
        migrations.AddField(
            model_name="detallerecurso",
            name="empresa",
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
