# Generated by Django 5.2.12 on 2026-05-24 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe_diario', '0004_detallerecurso_empresa'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='anexofoto',
            options={'ordering': ['seccion', 'posicion', 'orden']},
        ),
        migrations.AddField(
            model_name='anexofoto',
            name='posicion',
            field=models.PositiveSmallIntegerField(default=0, help_text='Posición en la cuadrícula 4x6 (1-24)'),
        ),
        migrations.AddField(
            model_name='informediario',
            name='status',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('aprobado', 'Aprobado')], default='borrador', max_length=20),
        ),
        migrations.CreateModel(
            name='MaquinariaLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('orden', models.IntegerField(default=0)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maquinaria_libre', to='informe_diario.informediario')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalLibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('orden', models.IntegerField(default=0)),
                ('informe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_libre', to='informe_diario.informediario')),
            ],
        ),
    ]
