# Generated by Django 5.2.12 on 2026-05-31 01:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe_diario', '0005_alter_anexofoto_options_anexofoto_posicion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detallerecurso',
            name='observacion',
        ),
        migrations.AddField(
            model_name='detallerecurso',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='maquinarialibre',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AddField(
            model_name='personallibre',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas'),
        ),
        migrations.AlterField(
            model_name='anexofoto',
            name='posicion',
            field=models.PositiveSmallIntegerField(default=0, help_text='Posición en la cuadrícula 4x6 (1-24). 0 si no está asignada.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(24)]),
        ),
    ]
