# Generated by Django 5.2.12 on 2026-06-13 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe_diario', '0006_remove_detallerecurso_observacion_and_more'),
        ('rrhh', '0004_conceptonomina_periodonomina_nomina_detallenomina'),
    ]

    operations = [
        migrations.AddField(
            model_name='informediario',
            name='elaborado_por_texto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Elaborado por (texto)'),
        ),
        migrations.AddField(
            model_name='informediario',
            name='revisado_por_texto',
            field=models.CharField(blank=True, max_length=200, verbose_name='Revisado por (texto)'),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='elaborado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_elaborados', to='rrhh.empleado', verbose_name='Elaborado por'),
        ),
        migrations.AlterField(
            model_name='informediario',
            name='revisado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_revisados', to='rrhh.empleado', verbose_name='Revisado por'),
        ),
    ]
