# Generated by Django 5.2.12 on 2026-06-14 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe_diario', '0009_nullable_proyecto_anexo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anexofoto',
            name='posicion',
            field=models.PositiveSmallIntegerField(default=0, help_text='Posición en la cuadrícula 4x6 (1-48). 0 si no está asignada.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(48)]),
        ),
    ]
