# Generated by Django 5.2.12 on 2026-06-21 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('informe_diario', '0010_increase_posicion_max_to_48'),
        ('rrhh', '0005_empleado_firma'),
    ]

    operations = [
        migrations.AddField(
            model_name='informediario',
            name='profesional_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_profesional_1', to='rrhh.empleado', verbose_name='Profesional No 1'),
        ),
        migrations.AddField(
            model_name='informediario',
            name='profesional_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_profesional_2', to='rrhh.empleado', verbose_name='Profesional No 2'),
        ),
    ]
