# Generated by Django 5.2.12 on 2026-04-02 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspeccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(blank=True, max_length=50)),
                ('fecha_inspeccion', models.DateTimeField(auto_now_add=True)),
                ('resultado', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('inspector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Defecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=200)),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], default='baja', max_length=20)),
                ('cantidad_afectada', models.IntegerField(default=1)),
                ('inspeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defectos', to='calidad.inspeccion')),
            ],
        ),
        migrations.CreateModel(
            name='NormaCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('parametro', models.CharField(max_length=100)),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('unidad', models.CharField(blank=True, max_length=20)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.producto')),
            ],
        ),
    ]
