# Generated by Django 5.2.12 on 2026-04-04 20:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_programada', models.DateField()),
                ('tipo', models.CharField(choices=[('interna', 'Interna'), ('externa', 'Externa/Certificación')], default='interna', max_length=20)),
                ('alcance', models.CharField(help_text='Procesos a auditar', max_length=200)),
                ('auditor_lider', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('planeada', 'Planeada'), ('ejecucion', 'En Ejecución'), ('concluida', 'Concluida')], default='planeada', max_length=20)),
                ('hallazgos_totales', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EvaluacionProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor_nombre', models.CharField(max_length=200)),
                ('fecha_evaluacion', models.DateField(auto_now_add=True)),
                ('calificacion_calidad', models.IntegerField(default=100, help_text='Puntaje Base 100')),
                ('calificacion_tiempos', models.IntegerField(default=100, help_text='Puntaje Base 100')),
                ('aprobado', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoISO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código Doc')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('1_base', '1. Base del sistema (Manual/Política)'), ('2_procedimiento', '2. Procedimientos obligatorios'), ('3_instructivo', '3. Instructivos de fabricación'), ('4_registro', '4. Formatos y registros (Evidencia)')], max_length=20)),
                ('version', models.CharField(default='1.0', max_length=10)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('vigente', 'Vigente'), ('obsoleto', 'Obsoleto')], default='vigente', max_length=20)),
                ('fecha_aprobacion', models.DateField(auto_now_add=True)),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NoConformidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reporte', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField(verbose_name='Descripción de la No Conformidad')),
                ('origen', models.CharField(choices=[('auditoria', 'Auditoría Interna/Externa'), ('inspeccion', 'Inspección de Producto'), ('cliente', 'Queja de Cliente'), ('proveedor', 'Falla de Proveedor')], max_length=20)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('investigacion', 'En Investigación'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('inspeccion_relacionada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calidad.inspeccion')),
                ('reportado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nc_reportadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AccionCorrectiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('analisis_causa_raiz', models.TextField(blank=True, help_text='5 Porqués o Ishikawa')),
                ('plan_accion', models.TextField(verbose_name='Plan de Acción')),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('por_iniciar', 'Por Iniciar'), ('en_curso', 'En Curso'), ('verificada', 'Verificada/Cerrada')], default='por_iniciar', max_length=20)),
                ('responsable', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('no_conformidad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capa', to='calidad.noconformidad')),
            ],
        ),
    ]
