# Generated by Django 5.2.12 on 2026-04-04 21:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0002_auditoria_evaluacionproveedor_documentoiso_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoISO9001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True, verbose_name='Código Formato')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Formato')),
                ('tipo', models.CharField(choices=[('manual_calidad', 'Manual de Calidad'), ('procedimiento', 'Procedimiento Operativo'), ('instructivo', 'Instructivo de Trabajo'), ('formato_registro', 'Formato/Registro'), ('checklist', 'Checklist de Verificación'), ('informe_auditoria', 'Informe de Auditoría'), ('accion_correctiva', 'Acción Correctiva'), ('evaluacion_proveedor', 'Evaluación Proveedor'), ('control_proceso', 'Control de Proceso'), ('especificacion_tecnica', 'Especificación Técnica')], max_length=30, verbose_name='Tipo de Formato')),
                ('version', models.CharField(default='1.0', max_length=10, verbose_name='Versión')),
                ('fecha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('fecha_aprobacion', models.DateField(blank=True, null=True, verbose_name='Fecha Aprobación')),
                ('fecha_revision', models.DateField(blank=True, null=True, verbose_name='Fecha Próxima Revisión')),
                ('modulo_relacionado', models.CharField(choices=[('calidad', 'Módulo Calidad'), ('produccion', 'Módulo Producción'), ('compras', 'Módulo Compras'), ('ventas', 'Módulo Ventas'), ('mrp', 'MRP/SAP'), ('kave', 'Diseño Transformadores'), ('inventarios', 'Inventarios'), ('mantenimiento', 'Mantenimiento'), ('rrhh', 'Recursos Humanos'), ('finanzas', 'Finanzas'), ('contabilidad', 'Contabilidad'), ('multi_empresa', 'Multi-Empresa')], max_length=50, verbose_name='Módulo ERP')),
                ('proceso_afectado', models.CharField(max_length=200, verbose_name='Proceso Afectado')),
                ('motivo_cambio', models.TextField(blank=True, verbose_name='Motivo del Cambio')),
                ('descripcion', models.TextField(verbose_name='Descripción del Formato')),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'En Revisión'), ('aprobacion', 'En Aprobación'), ('vigente', 'Vigente'), ('obsoleto', 'Obsoleto')], default='borrador', max_length=20, verbose_name='Estado')),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='iso9001/formatos/', verbose_name='Archivo PDF')),
                ('archivo_word', models.FileField(blank=True, null=True, upload_to='iso9001/editables/', verbose_name='Archivo Editable')),
                ('archivo_plantilla', models.FileField(blank=True, null=True, upload_to='iso9001/plantillas/', verbose_name='Plantilla')),
                ('frecuencia_actualizacion', models.IntegerField(default=12, help_text='Meses para próxima revisión', verbose_name='Frecuencia Actualización')),
                ('obligatorio', models.BooleanField(default=True, verbose_name='Formato Obligatorio')),
                ('requiere_aprobacion', models.BooleanField(default=True, verbose_name='Requiere Aprobación')),
                ('ultima_auditoria', models.DateField(blank=True, null=True, verbose_name='Última Auditoría')),
                ('conformidades', models.IntegerField(default=0, verbose_name='Conformidades')),
                ('no_conformidades', models.IntegerField(default=0, verbose_name='No Conformidades')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('aprobado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formatos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formatos_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Formato ISO 9001',
                'verbose_name_plural': 'Formatos ISO 9001',
                'ordering': ['modulo_relacionado', 'codigo'],
            },
        ),
        migrations.CreateModel(
            name='ProcesoISO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_proceso', models.CharField(max_length=200, verbose_name='Nombre del Proceso')),
                ('modulo_erp', models.CharField(choices=[('calidad', 'Módulo Calidad'), ('produccion', 'Módulo Producción'), ('compras', 'Módulo Compras'), ('ventas', 'Módulo Ventas'), ('mrp', 'MRP/SAP'), ('kave', 'Diseño Transformadores'), ('inventarios', 'Inventarios'), ('mantenimiento', 'Mantenimiento'), ('rrhh', 'Recursos Humanos'), ('finanzas', 'Finanzas'), ('contabilidad', 'Contabilidad'), ('multi_empresa', 'Multi-Empresa')], max_length=50, verbose_name='Módulo ERP')),
                ('descripcion', models.TextField(verbose_name='Descripción del Proceso')),
                ('indicadores', models.JSONField(default=dict, verbose_name='Indicadores KPI')),
                ('frecuencia_auditoria', models.IntegerField(default=12, verbose_name='Frecuencia Auditoría (meses)')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('mejora', 'En Mejora'), ('suspendido', 'Suspendido')], default='activo', max_length=20, verbose_name='Estado del Proceso')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('formatos_iso', models.ManyToManyField(blank=True, related_name='procesos_asociados', to='calidad.formatoiso9001')),
                ('responsable_proceso', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable del Proceso')),
            ],
            options={
                'verbose_name': 'Proceso ISO',
                'verbose_name_plural': 'Procesos ISO',
                'ordering': ['modulo_erp', 'nombre_proceso'],
            },
        ),
        migrations.CreateModel(
            name='TrazabilidadISO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo_erp', models.CharField(max_length=50, verbose_name='Módulo ERP')),
                ('registro_id', models.IntegerField(verbose_name='ID del Registro')),
                ('accion', models.CharField(choices=[('creacion', 'Creación'), ('modificacion', 'Modificación'), ('aprobacion', 'Aprobación'), ('consulta', 'Consulta'), ('auditoria', 'Auditoría')], max_length=50, verbose_name='Acción Realizada')),
                ('fecha_uso', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Uso')),
                ('detalles', models.JSONField(blank=True, default=dict, verbose_name='Detalles Adicionales')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.formatoiso9001', verbose_name='Formato ISO')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Trazabilidad ISO',
                'verbose_name_plural': 'Trazabilidad ISO',
                'ordering': ['-fecha_uso'],
            },
        ),
        migrations.AddIndex(
            model_name='formatoiso9001',
            index=models.Index(fields=['modulo_relacionado', 'estado'], name='calidad_for_modulo__b099e5_idx'),
        ),
        migrations.AddIndex(
            model_name='formatoiso9001',
            index=models.Index(fields=['codigo', 'version'], name='calidad_for_codigo_a98ae1_idx'),
        ),
        migrations.AddIndex(
            model_name='formatoiso9001',
            index=models.Index(fields=['tipo', 'estado'], name='calidad_for_tipo_bdfaa0_idx'),
        ),
        migrations.AddIndex(
            model_name='trazabilidadiso',
            index=models.Index(fields=['formato', '-fecha_uso'], name='calidad_tra_formato_a52767_idx'),
        ),
        migrations.AddIndex(
            model_name='trazabilidadiso',
            index=models.Index(fields=['modulo_erp', '-fecha_uso'], name='calidad_tra_modulo__62fd19_idx'),
        ),
        migrations.AddIndex(
            model_name='trazabilidadiso',
            index=models.Index(fields=['usuario', '-fecha_uso'], name='calidad_tra_usuario_a13df9_idx'),
        ),
    ]
