# Generated by Django 5.2.12 on 2026-04-02 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('activa', 'Activa'), ('pausada', 'Pausada'), ('finalizada', 'Finalizada')], default='planificada', max_length=20)),
                ('canales', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='Segmento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('criterios', models.JSONField(default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('empresa', models.CharField(blank=True, max_length=200)),
                ('fuente', models.CharField(choices=[('campana', 'Campaña'), ('referido', 'Referido'), ('web', 'Sitio Web'), ('redes_sociales', 'Redes Sociales'), ('otro', 'Otro')], default='otro', max_length=50)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('contactado', 'Contactado'), ('calificado', 'Calificado'), ('propuesta', 'Propuesta Enviada'), ('ganado', 'Ganado'), ('perdido', 'Perdido')], default='nuevo', max_length=20)),
                ('puntuacion', models.IntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('campana', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.campana')),
            ],
        ),
        migrations.AddField(
            model_name='campana',
            name='segmento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marketing.segmento'),
        ),
    ]
