# Generated by Django 5.2.12 on 2026-04-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='numero_campana',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
