# Generated by Django 5.2.12 on 2026-04-25 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0007_cotizacion_forma_pago_cotizacion_garantia_and_more'),
        ('marketing', '0002_campana_numero_campana'),
    ]

    operations = [
        migrations.AddField(
            model_name='campana',
            name='conversiones',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='campana',
            name='leads_generados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='cliente_convertido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm.cliente'),
        ),
    ]
