# Generated by Django 5.2.12 on 2026-04-02 20:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('capacidad_horas_dia', models.DecimalField(decimal_places=2, default=8.0, max_digits=5)),
                ('eficiencia', models.DecimalField(decimal_places=2, default=100.0, max_digits=5)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Centro de Trabajo',
                'verbose_name_plural': 'Centros de Trabajo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='EjecucionMRP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ejecucion', models.DateTimeField(auto_now_add=True)),
                ('fecha_plan_desde', models.DateField()),
                ('fecha_plan_hasta', models.DateField()),
                ('estado', models.CharField(choices=[('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('error', 'Error')], default='en_progreso', max_length=20)),
                ('mensaje', models.TextField(blank=True)),
                ('parametros', models.JSONField(default=dict)),
                ('resumen', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Ejecución MRP',
                'verbose_name_plural': 'Ejecuciones MRP',
                'ordering': ['-fecha_ejecucion'],
            },
        ),
        migrations.CreateModel(
            name='PlanMaestroProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cantidad_planificada', models.IntegerField()),
                ('cantidad_real', models.IntegerField(default=0)),
                ('estado', models.CharField(choices=[('planificado', 'Planificado'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='planificado', max_length=20)),
                ('prioridad', models.IntegerField(default=5)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.producto')),
            ],
            options={
                'verbose_name': 'Plan Maestro de Producción',
                'verbose_name_plural': 'Planes Maestros de Producción',
                'ordering': ['-fecha_inicio', '-prioridad'],
            },
        ),
        migrations.CreateModel(
            name='RequerimientoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_requerimiento', models.DateField()),
                ('tipo_requerimiento', models.CharField(choices=[('bruto', 'Requerimiento Bruto'), ('neto', 'Requerimiento Neto'), ('orden_compra', 'Orden Compra'), ('orden_produccion', 'Orden Producción')], default='neto', max_length=20)),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_ordenada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cantidad_pendiente', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('ordenado', 'Ordenado'), ('recibido', 'Recibido'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20)),
                ('origen', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.producto')),
            ],
            options={
                'verbose_name': 'Requerimiento de Material',
                'verbose_name_plural': 'Requerimientos de Materiales',
                'ordering': ['fecha_requerimiento', 'producto'],
            },
        ),
        migrations.CreateModel(
            name='ListaMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unidad_medida', models.CharField(default='UN', max_length=20)),
                ('nivel', models.IntegerField(default=1)),
                ('porcentaje_desperdicio', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tiempo_espera', models.IntegerField(default=0)),
                ('efectiva_desde', models.DateField(default=django.utils.timezone.now)),
                ('efectiva_hasta', models.DateField(blank=True, null=True)),
                ('tipo_componente', models.CharField(choices=[('material', 'Material'), ('subensamble', 'Subensamble'), ('servicio', 'Servicio')], default='material', max_length=20)),
                ('producto_hijo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms_hijo', to='inventarios.producto')),
                ('producto_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms_padre', to='inventarios.producto')),
            ],
            options={
                'verbose_name': 'Lista de Materiales',
                'verbose_name_plural': 'Listas de Materiales',
                'ordering': ['producto_padre', 'nivel'],
                'unique_together': {('producto_padre', 'producto_hijo', 'efectiva_desde')},
            },
        ),
        migrations.CreateModel(
            name='PlanCapacidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('capacidad_disponible', models.DecimalField(decimal_places=2, max_digits=8)),
                ('carga_requerida', models.DecimalField(decimal_places=2, max_digits=8)),
                ('carga_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('estado', models.CharField(choices=[('subutilizado', 'Subutilizado'), ('optimo', 'Óptimo'), ('sobrecargado', 'Sobrecargado')], default='optimo', max_length=20)),
                ('centro_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.centrotrabajo')),
            ],
            options={
                'verbose_name': 'Plan de Capacidad',
                'verbose_name_plural': 'Planes de Capacidad',
                'ordering': ['fecha', 'centro_trabajo'],
                'unique_together': {('centro_trabajo', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='RutaManufactura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secuencia', models.IntegerField()),
                ('descripcion_operacion', models.CharField(max_length=200)),
                ('tiempo_preparacion', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tiempo_operacion', models.DecimalField(decimal_places=2, max_digits=8)),
                ('eficiencia', models.DecimalField(decimal_places=2, default=100, max_digits=5)),
                ('setup_fijo', models.BooleanField(default=False)),
                ('overlapping', models.BooleanField(default=False)),
                ('centro_trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mrp.centrotrabajo')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutas', to='inventarios.producto')),
            ],
            options={
                'verbose_name': 'Ruta de Manufactura',
                'verbose_name_plural': 'Rutas de Manufactura',
                'ordering': ['producto', 'secuencia'],
                'unique_together': {('producto', 'secuencia')},
            },
        ),
    ]
