# Generated by Django 5.2.12 on 2026-06-08 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contabilidad', '0005_centrocosto_controlauditoria_retencion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndicadorTesoreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Indicador')),
                ('codigo', models.CharField(max_length=30, unique=True, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('liquidez', 'Liquidez'), ('solvencia', 'Solvencia'), ('cobertura', 'Cobertura'), ('eficiencia', 'Eficiencia')], max_length=20, verbose_name='Tipo')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('formula', models.TextField(verbose_name='Fórmula de Cálculo')),
                ('valor_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Mínimo Aceptable')),
                ('valor_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Máximo Aceptable')),
                ('valor_objetivo', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Valor Objetivo')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Indicador Tesorería',
                'verbose_name_plural': 'Indicadores Tesorería',
                'ordering': ['tipo', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('bancolombia', 'Bancolombia'), ('bbva', 'BBVA'), ('davivienda', 'Davivienda'), ('bogota', 'Banco de Bogotá'), ('occidente', 'Banco de Occidente'), ('colpatria', 'Colpatria'), ('pichincha', 'Banco Pichincha'), ('nequi', 'Nequi'), ('otro', 'Otro')], max_length=50, verbose_name='Banco')),
                ('numero_cuenta', models.CharField(max_length=30, unique=True, verbose_name='Número de Cuenta')),
                ('tipo_cuenta', models.CharField(choices=[('corriente', 'Corriente'), ('ahorro', 'Ahorro'), ('monedasextranjeras', 'Moneda Extranjera')], max_length=20, verbose_name='Tipo de Cuenta')),
                ('titulares', models.CharField(max_length=200, verbose_name='Titulares')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Inicial')),
                ('saldo_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Sistema')),
                ('saldo_banco', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo del Banco')),
                ('activa', models.BooleanField(default=True, verbose_name='Activa')),
                ('fecha_apertura', models.DateField(auto_now_add=True, verbose_name='Fecha Apertura')),
                ('ultimo_movimiento', models.DateField(blank=True, null=True, verbose_name='Último Movimiento')),
                ('saldo_minimo_permitido', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Saldo Mínimo')),
                ('saldo_maximo_permitido', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Saldo Máximo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('cuenta_contable', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.cuenta', verbose_name='Cuenta Contable')),
            ],
            options={
                'verbose_name': 'Cuenta Bancaria',
                'verbose_name_plural': 'Cuentas Bancarias',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ConciliacionBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_conciliacion', models.CharField(max_length=30, unique=True, verbose_name='Número Conciliación')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('fecha_conciliacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Conciliación')),
                ('saldo_inicial_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Inicial Sistema')),
                ('saldo_inicial_banco', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Inicial Banco')),
                ('total_ingresos_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Ingresos Sistema')),
                ('total_ingresos_banco', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Ingresos Banco')),
                ('total_egresos_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Egresos Sistema')),
                ('total_egresos_banco', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Egresos Banco')),
                ('saldo_final_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Final Sistema')),
                ('saldo_final_banco', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Final Banco')),
                ('diferencia_total', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Diferencia Total')),
                ('estado', models.CharField(choices=[('en_proceso', 'En Proceso'), ('completada', 'Completada'), ('reversada', 'Reversada')], default='en_proceso', max_length=20, verbose_name='Estado')),
                ('conciliada', models.BooleanField(default=False, verbose_name='¿Conciliada?')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario_conciliador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Conciliador')),
                ('cuenta_banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tesoreria.cuentabancaria', verbose_name='Cuenta Bancaria')),
            ],
            options={
                'verbose_name': 'Conciliación Bancaria',
                'verbose_name_plural': 'Conciliaciones Bancarias',
                'ordering': ['-fecha_fin'],
            },
        ),
        migrations.CreateModel(
            name='MovimientoTesoreria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_movimiento', models.CharField(max_length=30, unique=True, verbose_name='Número Movimiento')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('fecha_valor', models.DateField(blank=True, null=True, verbose_name='Fecha Valor')),
                ('tipo', models.CharField(choices=[('ingreso', 'Ingreso'), ('egreso', 'Egreso'), ('transferencia', 'Transferencia'), ('retencion', 'Retención'), ('devolucion', 'Devolución')], max_length=20, verbose_name='Tipo')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('referencia_bancaria', models.CharField(blank=True, max_length=100, verbose_name='Referencia Banco (Cheque, Referencia)')),
                ('documento_origen', models.CharField(blank=True, max_length=100, verbose_name='Documento Origen (Factura, OC)')),
                ('tercero_nombre', models.CharField(blank=True, max_length=200, verbose_name='Nombre Tercero')),
                ('tercero_nit', models.CharField(blank=True, max_length=20, verbose_name='NIT Tercero')),
                ('tercero_banco', models.CharField(blank=True, max_length=100, verbose_name='Banco Tercero')),
                ('tercero_cuenta', models.CharField(blank=True, max_length=30, verbose_name='Cuenta Tercero')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('conciliado', 'Conciliado'), ('reversado', 'Reversado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('conciliado', models.BooleanField(default=False, verbose_name='¿Conciliado?')),
                ('fecha_conciliacion', models.DateField(blank=True, null=True, verbose_name='Fecha Conciliación')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('asiento_contable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.asientocontable', verbose_name='Asiento Contable')),
                ('cuenta_banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimientos', to='tesoreria.cuentabancaria', verbose_name='Cuenta Bancaria')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_tesoreria_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento de Tesorería',
                'verbose_name_plural': 'Movimientos de Tesorería',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cheque', models.CharField(max_length=20, unique=True, verbose_name='Número Cheque')),
                ('tipo', models.CharField(choices=[('emitido', 'Emitido'), ('recibido', 'Recibido')], max_length=20, verbose_name='Tipo')),
                ('fecha_emision', models.DateField(verbose_name='Fecha Emisión')),
                ('fecha_vencimiento', models.DateField(verbose_name='Fecha Vencimiento')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Monto')),
                ('beneficiario', models.CharField(max_length=200, verbose_name='Beneficiario')),
                ('concepto', models.CharField(max_length=255, verbose_name='Concepto')),
                ('estado', models.CharField(choices=[('emitido', 'Emitido'), ('entregado', 'Entregado'), ('cobrado', 'Cobrado'), ('devuelto', 'Devuelto'), ('cancelado', 'Cancelado')], default='emitido', max_length=20, verbose_name='Estado')),
                ('fecha_cobro', models.DateField(blank=True, null=True, verbose_name='Fecha Cobro')),
                ('razon_devolucion', models.TextField(blank=True, verbose_name='Razón Devolución')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cuenta_banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cheques', to='tesoreria.cuentabancaria', verbose_name='Cuenta Bancaria')),
                ('movimiento_tesoreria', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tesoreria.movimientotesoreria', verbose_name='Movimiento Tesorería')),
            ],
            options={
                'verbose_name': 'Cheque',
                'verbose_name_plural': 'Cheques',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='ProyeccionFlujoCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_proyeccion', models.CharField(max_length=30, unique=True, verbose_name='Número Proyección')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha Inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha Fin')),
                ('escenario', models.CharField(choices=[('pesimista', 'Pesimista'), ('conservador', 'Conservador'), ('optimista', 'Optimista')], default='conservador', max_length=20, verbose_name='Escenario')),
                ('saldo_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Inicial')),
                ('ingresos_proyectados', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Ingresos Proyectados')),
                ('egresos_proyectados', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Egresos Proyectados')),
                ('saldo_final_proyectado', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Saldo Final Proyectado')),
                ('dias_cobertura', models.IntegerField(blank=True, null=True, verbose_name='Días de Cobertura')),
                ('alerta_insolvencia', models.BooleanField(default=False, verbose_name='¿Alerta de Insolvencia?')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cuenta_banco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tesoreria.cuentabancaria', verbose_name='Cuenta Bancaria')),
                ('usuario_creador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Proyección Flujo Caja',
                'verbose_name_plural': 'Proyecciones Flujo Caja',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='RegistroIndicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('valor_real', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Real')),
                ('estado', models.CharField(choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('aceptable', 'Aceptable'), ('alerta', 'Alerta'), ('crítico', 'Crítico')], max_length=20, verbose_name='Estado')),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='tesoreria.indicadortesoreria')),
            ],
            options={
                'verbose_name': 'Registro Indicador',
                'verbose_name_plural': 'Registros Indicadores',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddIndex(
            model_name='movimientotesoreria',
            index=models.Index(fields=['cuenta_banco', 'fecha'], name='tesoreria_m_cuenta__dddba2_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientotesoreria',
            index=models.Index(fields=['estado', 'conciliado'], name='tesoreria_m_estado_712ae4_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientotesoreria',
            index=models.Index(fields=['numero_movimiento'], name='tesoreria_m_numero__147433_idx'),
        ),
    ]
