# Generated by Django 5.2.12 on 2026-06-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='estado_dian',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada DIAN'), ('validada', 'Validada DIAN'), ('rechazada', 'Rechazada DIAN'), ('error_emision', 'Error de Emisión')], default='borrador', max_length=20),
        ),
    ]
