# Generated by Django 5.2.12 on 2026-03-29 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AFP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "AFP (Pensión)",
                "db_table": "rrhh_afp",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="ARL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "ARL",
                "db_table": "rrhh_arl",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="CajaCompensacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Caja de Compensación",
                "db_table": "rrhh_caja_compensacion",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Departamento",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Departamento",
                "db_table": "rrhh_departamento",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="EPS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=120)),
                ("codigo_habilitacion", models.CharField(blank=True, max_length=20)),
                ("activa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "EPS",
                "verbose_name_plural": "EPS",
                "db_table": "rrhh_eps",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Cargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True)),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cargos",
                        to="rrhh.departamento",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cargo",
                "db_table": "rrhh_cargo",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Empleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_documento",
                    models.CharField(
                        choices=[
                            ("CC", "Cédula de Ciudadanía"),
                            ("CE", "Cédula de Extranjería"),
                            ("PA", "Pasaporte"),
                            ("TI", "Tarjeta de Identidad"),
                            ("NIT", "NIT"),
                        ],
                        default="CC",
                        max_length=5,
                    ),
                ),
                ("numero_documento", models.CharField(max_length=20, unique=True)),
                ("primer_nombre", models.CharField(max_length=60)),
                ("segundo_nombre", models.CharField(blank=True, max_length=60)),
                ("primer_apellido", models.CharField(max_length=60)),
                ("segundo_apellido", models.CharField(blank=True, max_length=60)),
                ("fecha_nacimiento", models.DateField()),
                ("lugar_nacimiento", models.CharField(blank=True, max_length=100)),
                (
                    "genero",
                    models.CharField(
                        choices=[
                            ("M", "Masculino"),
                            ("F", "Femenino"),
                            ("O", "Otro"),
                            ("NI", "No informa"),
                        ],
                        max_length=2,
                    ),
                ),
                (
                    "estado_civil",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "Soltero/a"),
                            ("C", "Casado/a"),
                            ("U", "Unión libre"),
                            ("D", "Divorciado/a"),
                            ("V", "Viudo/a"),
                        ],
                        max_length=2,
                    ),
                ),
                ("nacionalidad", models.CharField(default="Colombiana", max_length=60)),
                (
                    "foto",
                    models.ImageField(blank=True, null=True, upload_to="rrhh/fotos/"),
                ),
                ("correo_personal", models.EmailField(blank=True, max_length=254)),
                ("correo_corporativo", models.EmailField(blank=True, max_length=254)),
                ("telefono_trabajo", models.CharField(blank=True, max_length=20)),
                ("telefono_personal", models.CharField(blank=True, max_length=20)),
                ("telefono_movil", models.CharField(blank=True, max_length=20)),
                ("direccion", models.CharField(blank=True, max_length=200)),
                ("barrio", models.CharField(blank=True, max_length=100)),
                ("ciudad", models.CharField(blank=True, max_length=100)),
                (
                    "departamento_residencia",
                    models.CharField(blank=True, max_length=100),
                ),
                ("codigo_postal", models.CharField(blank=True, max_length=10)),
                ("pais", models.CharField(default="Colombia", max_length=60)),
                ("fecha_ingreso", models.DateField()),
                ("fecha_retiro", models.DateField(blank=True, null=True)),
                (
                    "tipo_contrato",
                    models.CharField(
                        choices=[
                            ("IND", "Término indefinido"),
                            ("FIJ", "Término fijo"),
                            ("OBR", "Obra o labor"),
                            ("APR", "Aprendizaje"),
                            ("SER", "Prestación de servicios"),
                        ],
                        default="IND",
                        max_length=3,
                    ),
                ),
                (
                    "tipo_salario",
                    models.CharField(
                        choices=[
                            ("FIJ", "Salario fijo"),
                            ("VAR", "Salario variable"),
                            ("INT", "Salario integral"),
                        ],
                        default="FIJ",
                        max_length=3,
                    ),
                ),
                (
                    "salario_basico",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("auxilio_transporte", models.BooleanField(default=True)),
                ("pagina_web", models.URLField(blank=True)),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("ACT", "Activo"),
                            ("INA", "Inactivo"),
                            ("VAC", "En vacaciones"),
                            ("INC", "Incapacitado"),
                            ("LIC", "En licencia"),
                            ("RET", "Retirado"),
                        ],
                        default="ACT",
                        max_length=3,
                    ),
                ),
                ("notas", models.TextField(blank=True)),
                (
                    "nivel_riesgo_arl",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("I", "Nivel I - Mínimo"),
                            ("II", "Nivel II - Bajo"),
                            ("III", "Nivel III - Medio"),
                            ("IV", "Nivel IV - Alto"),
                            ("V", "Nivel V - Máximo"),
                        ],
                        default="I",
                        max_length=3,
                    ),
                ),
                ("fondo_cesantias", models.CharField(blank=True, max_length=120)),
                (
                    "banco",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BANCOLOMBIA", "Bancolombia"),
                            ("DAVIVIENDA", "Davivienda"),
                            ("BOGOTA", "Banco de Bogotá"),
                            ("OCCIDENTE", "Banco de Occidente"),
                            ("BBVA", "BBVA"),
                            ("NEQUI", "Nequi"),
                            ("DAVIPLATA", "Daviplata"),
                            ("OTRO", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "tipo_cuenta",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("AHO", "Cuenta de ahorros"),
                            ("CTE", "Cuenta corriente"),
                        ],
                        max_length=3,
                    ),
                ),
                ("numero_cuenta", models.CharField(blank=True, max_length=30)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("actualizado_en", models.DateTimeField(auto_now=True)),
                (
                    "afp",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="empleados",
                        to="rrhh.afp",
                    ),
                ),
                (
                    "arl",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="empleados",
                        to="rrhh.arl",
                    ),
                ),
                (
                    "caja_compensacion",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="empleados",
                        to="rrhh.cajacompensacion",
                    ),
                ),
                (
                    "cargo",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="empleados",
                        to="rrhh.cargo",
                    ),
                ),
                (
                    "departamento",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="empleados",
                        to="rrhh.departamento",
                    ),
                ),
                (
                    "eps",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="empleados",
                        to="rrhh.eps",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empleado",
                "verbose_name_plural": "Empleados",
                "db_table": "rrhh_empleado",
                "ordering": ["primer_apellido", "primer_nombre"],
            },
        ),
        migrations.CreateModel(
            name="ContactoEmergencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=150)),
                (
                    "parentesco",
                    models.CharField(
                        choices=[
                            ("CON", "Cónyuge / Compañero(a)"),
                            ("PAD", "Padre"),
                            ("MAD", "Madre"),
                            ("HIJ", "Hijo/a"),
                            ("HER", "Hermano/a"),
                            ("AMI", "Amigo/a"),
                            ("OTR", "Otro"),
                        ],
                        max_length=3,
                    ),
                ),
                ("telefono_principal", models.CharField(max_length=20)),
                ("telefono_alternativo", models.CharField(blank=True, max_length=20)),
                ("correo", models.EmailField(blank=True, max_length=254)),
                ("es_principal", models.BooleanField(default=False)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contactos_emergencia",
                        to="rrhh.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contacto de emergencia",
                "verbose_name_plural": "Contactos de emergencia",
                "db_table": "rrhh_contacto_emergencia",
            },
        ),
    ]
