# Generated by Django 5.2.12 on 2026-03-07 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('documento_identidad', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_contratacion', models.DateField()),
                ('cargo', models.CharField(max_length=100)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('departamento', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('vacaciones', 'En Vacaciones'), ('incapacidad', 'Incapacidad'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('hora_salida', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('retraso', 'Retraso')], default='presente', max_length=20)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rrhh.empleado')),
            ],
        ),
    ]
