# Generated by Django 5.2.12 on 2026-03-30 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="empleado",
            name="cargo",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="empleado",
            name="departamento",
            field=models.CharField(blank=True, default="", max_length=100),
            preserve_default=False,
        ),
    ]
