# Generated by Django 5.2.12 on 2026-04-01 22:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0002_alter_empleado_cargo_alter_empleado_departamento"),
    ]

    operations = [
        migrations.CreateModel(
            name="CentroCosto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=20, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Centro de Costo",
                "db_table": "rrhh_centro_costo",
                "ordering": ["codigo"],
            },
        ),
        migrations.AlterModelOptions(
            name="contactoemergencia",
            options={"verbose_name": "Contacto de emergencia"},
        ),
        migrations.AlterModelOptions(
            name="eps",
            options={"ordering": ["nombre"], "verbose_name": "EPS"},
        ),
        migrations.RemoveField(
            model_name="empleado",
            name="pagina_web",
        ),
        migrations.AddField(
            model_name="cargo",
            name="salario_maximo",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="cargo",
            name="salario_minimo",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="categoria_licencia",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="empleado",
            name="estrato",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(6),
                ],
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="fecha_expedicion_doc",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="fecha_fin_periodo_prueba",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="fecha_vencimiento_contrato",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="empleado",
            name="grupo_sanguineo",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="horas_extras_autorizadas",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="empleado",
            name="jefe_directo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subordinados",
                to="rrhh.empleado",
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="lugar_expedicion_doc",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="empleado",
            name="motivo_retiro",
            field=models.CharField(
                blank=True,
                choices=[
                    ("REN", "Renuncia voluntaria"),
                    ("DES", "Despido sin justa causa"),
                    ("DJC", "Despido con justa causa"),
                    ("MUT", "Mutuo acuerdo"),
                    ("FCC", "Fin de contrato"),
                    ("FAL", "Fallecimiento"),
                    ("OTR", "Otro"),
                ],
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="periodicidad_pago",
            field=models.CharField(
                choices=[("SEM", "Semanal"), ("QUI", "Quincenal"), ("MEN", "Mensual")],
                default="MEN",
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="sede",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="empleado",
            name="talla_camisa",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="empleado",
            name="talla_casco",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="empleado",
            name="talla_pantalon",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="empleado",
            name="talla_zapatos",
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name="empleado",
            name="tiene_licencia",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="empleado",
            name="tipo_vivienda",
            field=models.CharField(
                blank=True,
                choices=[
                    ("PRO", "Propia"),
                    ("ARR", "Arrendada"),
                    ("FAM", "Familiar"),
                    ("OTR", "Otra"),
                ],
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="vencimiento_licencia",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="banco",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BANCOLOMBIA", "Bancolombia"),
                    ("DAVIVIENDA", "Davivienda"),
                    ("BOGOTA", "Banco de Bogotá"),
                    ("OCCIDENTE", "Banco de Occidente"),
                    ("BBVA", "BBVA"),
                    ("NEQUI", "Nequi"),
                    ("DAVIPLATA", "Daviplata"),
                    ("POPULAR", "Banco Popular"),
                    ("ITAU", "Itaú"),
                    ("SCOTIABANK", "Scotiabank Colpatria"),
                    ("OTRO", "Otro"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="empleado",
            name="nivel_riesgo_arl",
            field=models.CharField(
                blank=True,
                choices=[
                    ("I", "Nivel I - Mínimo"),
                    ("II", "Nivel II - Bajo"),
                    ("III", "Nivel III - Medio"),
                    ("IV", "Nivel IV - Alto"),
                    ("V", "Nivel V - Máximo"),
                ],
                max_length=3,
            ),
        ),
        migrations.AddField(
            model_name="empleado",
            name="centro_costo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="empleados",
                to="rrhh.centrocosto",
            ),
        ),
        migrations.CreateModel(
            name="Certificacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("entidad_emisora", models.CharField(max_length=150)),
                ("fecha_obtencion", models.DateField(blank=True, null=True)),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                ("numero_certificado", models.CharField(blank=True, max_length=50)),
                (
                    "archivo",
                    models.FileField(
                        blank=True, null=True, upload_to="rrhh/certificaciones/"
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificaciones",
                        to="rrhh.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Certificación / Curso",
                "db_table": "rrhh_certificacion",
            },
        ),
        migrations.CreateModel(
            name="Disciplinario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("LLA", "Llamado de atención verbal"),
                            ("MEM", "Memorando escrito"),
                            ("SUS", "Suspensión"),
                            ("DES", "Descargo"),
                            ("OTR", "Otro"),
                        ],
                        max_length=3,
                    ),
                ),
                ("fecha", models.DateField()),
                ("motivo", models.TextField()),
                ("dias_suspension", models.IntegerField(default=0)),
                ("firmado_empleado", models.BooleanField(default=False)),
                (
                    "archivo",
                    models.FileField(
                        blank=True, null=True, upload_to="rrhh/disciplinarios/"
                    ),
                ),
                ("creado_por", models.CharField(blank=True, max_length=100)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="disciplinarios",
                        to="rrhh.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Registro disciplinario",
                "db_table": "rrhh_disciplinario",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoEmpleado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("HV", "Hoja de vida"),
                            ("CC", "Copia cédula"),
                            ("DIP", "Diplomas / Actas"),
                            ("CER", "Certificaciones"),
                            ("EXM", "Examen médico"),
                            ("CTR", "Contrato firmado"),
                            ("AFI", "Afiliaciones SS"),
                            ("OTR", "Otro"),
                        ],
                        max_length=3,
                    ),
                ),
                ("nombre", models.CharField(max_length=150)),
                ("archivo", models.FileField(upload_to="rrhh/documentos/")),
                ("fecha_carga", models.DateTimeField(auto_now_add=True)),
                ("observaciones", models.CharField(blank=True, max_length=200)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos",
                        to="rrhh.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento del empleado",
                "db_table": "rrhh_documento_empleado",
                "ordering": ["-fecha_carga"],
            },
        ),
        migrations.CreateModel(
            name="Dotacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_entrega", models.DateField()),
                ("item", models.CharField(max_length=100)),
                ("talla", models.CharField(blank=True, max_length=10)),
                ("cantidad", models.IntegerField(default=1)),
                ("observaciones", models.CharField(blank=True, max_length=200)),
                ("recibido_por", models.CharField(blank=True, max_length=100)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dotaciones",
                        to="rrhh.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dotación",
                "db_table": "rrhh_dotacion",
                "ordering": ["-fecha_entrega"],
            },
        ),
        migrations.CreateModel(
            name="EPP",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("elemento", models.CharField(max_length=100)),
                ("marca", models.CharField(blank=True, max_length=60)),
                ("fecha_entrega", models.DateField()),
                ("fecha_vencimiento", models.DateField(blank=True, null=True)),
                ("cantidad", models.IntegerField(default=1)),
                ("devuelto", models.BooleanField(default=False)),
                ("fecha_devolucion", models.DateField(blank=True, null=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="epps",
                        to="rrhh.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "EPP",
                "verbose_name_plural": "EPP",
                "db_table": "rrhh_epp",
                "ordering": ["-fecha_entrega"],
            },
        ),
        migrations.CreateModel(
            name="EvaluacionDesempeno",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("año", models.IntegerField()),
                (
                    "periodo",
                    models.CharField(
                        choices=[
                            ("T1", "Primer trimestre"),
                            ("T2", "Segundo trimestre"),
                            ("T3", "Tercer trimestre"),
                            ("T4", "Cuarto trimestre"),
                            ("SEM1", "Primer semestre"),
                            ("SEM2", "Segundo semestre"),
                            ("ANU", "Anual"),
                        ],
                        max_length=5,
                    ),
                ),
                (
                    "calificacion",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("fortalezas", models.TextField(blank=True)),
                ("oportunidades_mejora", models.TextField(blank=True)),
                ("plan_accion", models.TextField(blank=True)),
                ("fecha_evaluacion", models.DateField()),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evaluaciones",
                        to="rrhh.empleado",
                    ),
                ),
                (
                    "evaluado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="evaluaciones_realizadas",
                        to="rrhh.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Evaluación de desempeño",
                "db_table": "rrhh_evaluacion_desempeno",
                "ordering": ["-año", "-periodo"],
            },
        ),
        migrations.CreateModel(
            name="ExamenMedico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ING", "Ingreso"),
                            ("PER", "Periódico"),
                            ("RET", "Retiro"),
                            ("POS", "Post-incapacidad"),
                        ],
                        max_length=3,
                    ),
                ),
                ("fecha", models.DateField()),
                (
                    "resultado",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("APT", "Apto"),
                            ("APR", "Apto con restricciones"),
                            ("NAP", "No apto"),
                        ],
                        max_length=3,
                    ),
                ),
                ("restricciones", models.TextField(blank=True)),
                ("entidad", models.CharField(blank=True, max_length=150)),
                ("medico", models.CharField(blank=True, max_length=150)),
                ("proxima_revision", models.DateField(blank=True, null=True)),
                (
                    "archivo",
                    models.FileField(blank=True, null=True, upload_to="rrhh/examenes/"),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="examenes_medicos",
                        to="rrhh.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Examen médico",
                "db_table": "rrhh_examen_medico",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="ExperienciaLaboral",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("empresa", models.CharField(max_length=150)),
                ("cargo", models.CharField(max_length=100)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                (
                    "salario",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "motivo_salida",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("REN", "Renuncia"),
                            ("DES", "Despido"),
                            ("FCC", "Fin de contrato"),
                            ("MUT", "Mutuo acuerdo"),
                            ("OTR", "Otro"),
                        ],
                        max_length=3,
                    ),
                ),
                ("jefe_nombre", models.CharField(blank=True, max_length=150)),
                ("jefe_telefono", models.CharField(blank=True, max_length=20)),
                ("funciones", models.TextField(blank=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="experiencia_laboral",
                        to="rrhh.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Experiencia laboral",
                "db_table": "rrhh_experiencia_laboral",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Familiar",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre_completo", models.CharField(max_length=150)),
                (
                    "parentesco",
                    models.CharField(
                        choices=[
                            ("CON", "Cónyuge / Compañero(a)"),
                            ("HIJ", "Hijo/a"),
                            ("PAD", "Padre"),
                            ("MAD", "Madre"),
                            ("HER", "Hermano/a"),
                            ("OTR", "Otro"),
                        ],
                        max_length=3,
                    ),
                ),
                ("tipo_documento", models.CharField(blank=True, max_length=5)),
                ("numero_documento", models.CharField(blank=True, max_length=20)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("depende_economicamente", models.BooleanField(default=False)),
                ("beneficiario_eps", models.BooleanField(default=False)),
                ("beneficiario_caja", models.BooleanField(default=False)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="familiares",
                        to="rrhh.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Familiar / Beneficiario",
                "db_table": "rrhh_familiar",
            },
        ),
        migrations.CreateModel(
            name="FormacionAcademica",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nivel",
                    models.CharField(
                        choices=[
                            ("PRI", "Primaria"),
                            ("SEC", "Secundaria / Bachillerato"),
                            ("TEC", "Técnico"),
                            ("TEN", "Tecnólogo"),
                            ("UNI", "Universitario"),
                            ("ESP", "Especialización"),
                            ("MAE", "Maestría"),
                            ("DOC", "Doctorado"),
                        ],
                        max_length=3,
                    ),
                ),
                ("titulo", models.CharField(max_length=150)),
                ("institucion", models.CharField(max_length=150)),
                ("año_inicio", models.IntegerField(blank=True, null=True)),
                ("año_fin", models.IntegerField(blank=True, null=True)),
                ("graduado", models.BooleanField(default=True)),
                ("tarjeta_profesional", models.CharField(blank=True, max_length=50)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="formacion_academica",
                        to="rrhh.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Formación académica",
                "db_table": "rrhh_formacion_academica",
            },
        ),
        migrations.CreateModel(
            name="HistorialCargo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cargo", models.CharField(max_length=100)),
                ("departamento", models.CharField(blank=True, max_length=100)),
                ("salario", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField(blank=True, null=True)),
                ("motivo_cambio", models.CharField(blank=True, max_length=200)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_cargos",
                        to="rrhh.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de cargo",
                "db_table": "rrhh_historial_cargo",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Idioma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("idioma", models.CharField(max_length=60)),
                (
                    "nivel_oral",
                    models.CharField(
                        choices=[
                            ("BAS", "Básico"),
                            ("INT", "Intermedio"),
                            ("AVZ", "Avanzado"),
                            ("NAT", "Nativo"),
                        ],
                        default="BAS",
                        max_length=3,
                    ),
                ),
                (
                    "nivel_escrito",
                    models.CharField(
                        choices=[
                            ("BAS", "Básico"),
                            ("INT", "Intermedio"),
                            ("AVZ", "Avanzado"),
                            ("NAT", "Nativo"),
                        ],
                        default="BAS",
                        max_length=3,
                    ),
                ),
                ("certificado", models.BooleanField(default=False)),
                ("nombre_certificado", models.CharField(blank=True, max_length=100)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="idiomas",
                        to="rrhh.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Idioma",
                "db_table": "rrhh_idioma",
            },
        ),
        migrations.CreateModel(
            name="Incapacidad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("ENF", "Enfermedad general"),
                            ("ACC", "Accidente de trabajo"),
                            ("ENP", "Enfermedad profesional"),
                            ("MAT", "Maternidad"),
                            ("PAT", "Paternidad"),
                            ("LUT", "Luto"),
                            ("OTR", "Otra"),
                        ],
                        max_length=3,
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("dias", models.IntegerField()),
                ("entidad_emisora", models.CharField(blank=True, max_length=100)),
                ("diagnostico", models.CharField(blank=True, max_length=200)),
                ("codigo_cie10", models.CharField(blank=True, max_length=10)),
                (
                    "archivo",
                    models.FileField(
                        blank=True, null=True, upload_to="rrhh/incapacidades/"
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incapacidades",
                        to="rrhh.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Incapacidad / Licencia",
                "db_table": "rrhh_incapacidad",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Vacaciones",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("dias_habiles", models.IntegerField()),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("SOL", "Solicitada"),
                            ("APR", "Aprobada"),
                            ("REC", "Rechazada"),
                            ("DIS", "Disfrutada"),
                        ],
                        default="SOL",
                        max_length=3,
                    ),
                ),
                ("observaciones", models.TextField(blank=True)),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "aprobado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vacaciones_aprobadas",
                        to="rrhh.empleado",
                    ),
                ),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacaciones",
                        to="rrhh.empleado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Vacaciones",
                "db_table": "rrhh_vacaciones",
                "ordering": ["-fecha_inicio"],
            },
        ),
    ]
