# Generated by Django 5.2.12 on 2026-04-24 21:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rrhh", "0003_centrocosto_alter_contactoemergencia_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConceptoNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("DEV", "Devengado"),
                            ("DED", "Deducción"),
                            ("PROV", "Provisiones"),
                        ],
                        max_length=4,
                    ),
                ),
                ("descripcion", models.TextField(blank=True)),
                ("es_base_cotizacion", models.BooleanField(default=False)),
                ("es_imponible", models.BooleanField(default=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Concepto de Nómina",
                "verbose_name_plural": "Conceptos de Nómina",
                "db_table": "rrhh_concepto_nomina",
                "ordering": ["tipo", "codigo"],
            },
        ),
        migrations.CreateModel(
            name="PeriodoNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("SEM", "Semanal"),
                            ("QUI", "Quincenal"),
                            ("MEN", "Mensual"),
                            ("BIM", "Bimensual"),
                        ],
                        default="MEN",
                        max_length=3,
                    ),
                ),
                ("fecha_inicio", models.DateField()),
                ("fecha_fin", models.DateField()),
                ("fecha_pago", models.DateField()),
                ("cerrado", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Período de Nómina",
                "verbose_name_plural": "Períodos de Nómina",
                "db_table": "rrhh_periodo_nomina",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="Nomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salario_base", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "dias_trabajados",
                    models.DecimalField(decimal_places=2, default=30, max_digits=5),
                ),
                (
                    "total_devengados",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_deducciones",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_provisiones",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("neto_pagar", models.DecimalField(decimal_places=2, max_digits=12)),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("procesada", models.BooleanField(default=False)),
                (
                    "empleado",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominas",
                        to="rrhh.empleado",
                    ),
                ),
                (
                    "periodo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominas",
                        to="rrhh.periodonomina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Nómina",
                "verbose_name_plural": "Nóminas",
                "db_table": "rrhh_nomina",
                "unique_together": {("periodo", "empleado")},
            },
        ),
        migrations.CreateModel(
            name="DetalleNomina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cantidad",
                    models.DecimalField(decimal_places=2, default=1, max_digits=8),
                ),
                (
                    "valor_unitario",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("valor", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "concepto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rrhh.conceptonomina",
                    ),
                ),
                (
                    "nomina",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="rrhh.nomina",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Nómina",
                "verbose_name_plural": "Detalles de Nómina",
                "db_table": "rrhh_detalle_nomina",
            },
        ),
    ]
