# Generated by Django 5.2.12 on 2026-04-25 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0002_periodo_contable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asientocontable',
            options={'ordering': ['-fecha', 'id'], 'verbose_name': 'Asiento Contable', 'verbose_name_plural': 'Asientos Contables'},
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'ordering': ['codigo'], 'verbose_name_plural': 'Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='movimientocontable',
            options={'ordering': ['asiento', 'id']},
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='contabilidad.cuenta'),
        ),
        migrations.AlterField(
            model_name='movimientocontable',
            name='cuenta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='contabilidad.cuenta'),
        ),
    ]
