# Generated by Django 5.2.12 on 2026-04-30 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0003_alter_asientocontable_options_alter_cuenta_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asientocontable',
            options={'ordering': ['-fecha'], 'verbose_name': 'Asiento Contable', 'verbose_name_plural': 'Libro Mayor (Asientos Contables)'},
        ),
        migrations.AlterModelOptions(
            name='cuenta',
            options={'ordering': ['codigo'], 'verbose_name': 'Cuenta Contable', 'verbose_name_plural': 'Catálogo de Cuentas'},
        ),
        migrations.AlterModelOptions(
            name='movimientocontable',
            options={'verbose_name': 'Movimiento Contable', 'verbose_name_plural': 'Movimientos Contables'},
        ),
        migrations.AlterModelOptions(
            name='periodocontable',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Período Contable', 'verbose_name_plural': 'Períodos Contables'},
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='padre',
        ),
        migrations.RemoveField(
            model_name='movimientocontable',
            name='asiento',
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, null=True, verbose_name='Datos Adicionales (JSON)'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='modulo_origen',
            field=models.CharField(default='sistema', max_length=50, verbose_name='Módulo de Origen'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso (Entrada de Dinero)'), ('egreso', 'Egreso (Salida de Dinero)'), ('ajuste', 'Ajuste Contable')], default='ingreso', max_length=10, verbose_name='Tipo de Movimiento'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Monto Total'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='activa',
            field=models.BooleanField(default=True, verbose_name='Cuenta Activa'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='cuenta_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='contabilidad.cuenta'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='asiento_contable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='contabilidad.asientocontable'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='descripcion',
            field=models.CharField(max_length=255, verbose_name='Concepto/Descripción'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha del Registro'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia Documento'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='total_debe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Débitos'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='total_haber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Total Créditos'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='codigo',
            field=models.CharField(max_length=20, unique=True, verbose_name='Código PUC'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='nivel',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Nivel (1=Mayor, 2=Auxiliar)'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Cuenta'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='tipo',
            field=models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('patrimonio', 'Patrimonio'), ('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=20, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AlterField(
            model_name='movimientocontable',
            name='debe',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Débito'),
        ),
        migrations.AlterField(
            model_name='movimientocontable',
            name='descripcion',
            field=models.CharField(blank=True, max_length=255, verbose_name='Descripción del Movimiento'),
        ),
        migrations.AlterField(
            model_name='movimientocontable',
            name='haber',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Crédito'),
        ),
        migrations.AlterField(
            model_name='periodocontable',
            name='asiento_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierre_periodo', to='contabilidad.asientocontable'),
        ),
        migrations.AlterField(
            model_name='periodocontable',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='periodocontable',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado')], default='abierto', max_length=10, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='periodocontable',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Cierre'),
        ),
        migrations.AlterField(
            model_name='periodocontable',
            name='fecha_fin',
            field=models.DateField(verbose_name='Fecha Fin'),
        ),
        migrations.AlterField(
            model_name='periodocontable',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='periodocontable',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre del Período'),
        ),
        migrations.AlterField(
            model_name='periodocontable',
            name='resultado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Resultado del Período'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['fecha', 'modulo_origen'], name='contabilida_fecha_81ecbf_idx'),
        ),
    ]
