# Generated by Django 5.2.12 on 2026-06-08 20:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0004_alter_asientocontable_options_alter_cuenta_options_and_more'),
        ('proyectos', '0003_proyectops_costo_comprometido_proyectops_costo_real_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Centro')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('tipo', models.CharField(choices=[('produccion', 'Producción'), ('administrativo', 'Administrativo'), ('ventas', 'Ventas'), ('distribucion', 'Distribución'), ('servicios', 'Servicios'), ('otro', 'Otro')], default='administrativo', max_length=20, verbose_name='Tipo')),
                ('presupuesto_anual', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Presupuesto Anual')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centros de Costo',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ControlAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('creacion', 'Creación'), ('modificacion', 'Modificación'), ('confirmacion', 'Confirmación'), ('reverso', 'Reverso'), ('acceso', 'Acceso a Información'), ('exportacion', 'Exportación'), ('otro', 'Otro')], max_length=20, verbose_name='Acción')),
                ('descripcion', models.TextField(verbose_name='Descripción de Cambios')),
                ('direccion_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Dirección IP')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='Fecha/Hora')),
                ('datos_anteriores', models.JSONField(blank=True, null=True, verbose_name='Datos Anteriores')),
                ('datos_nuevos', models.JSONField(blank=True, null=True, verbose_name='Datos Nuevos')),
            ],
            options={
                'verbose_name': 'Control de Auditoría',
                'verbose_name_plural': 'Controles de Auditoría',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Retencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=50, unique=True, verbose_name='Número Documento')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('tipo_retencion', models.CharField(choices=[('rte-fuente', 'Retención en la Fuente'), ('reteica', 'RETEICA'), ('rete-iva', 'RETE IVA'), ('otra', 'Otra')], max_length=20, verbose_name='Tipo Retencion')),
                ('tipo_tercero', models.CharField(choices=[('proveedor', 'Proveedor'), ('cliente', 'Cliente')], max_length=20, verbose_name='Tipo Tercero')),
                ('tercero_nit', models.CharField(max_length=20, verbose_name='NIT Tercero')),
                ('tercero_nombre', models.CharField(max_length=200, verbose_name='Nombre Tercero')),
                ('base_retencion', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Base Retención')),
                ('porcentaje_retencion', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Porcentaje (%)')),
                ('valor_retencion', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Retención')),
                ('documento_origen', models.CharField(max_length=100, verbose_name='Documento Origen (Factura, OC)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Retención',
                'verbose_name_plural': 'Retenciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AlterModelOptions(
            name='movimientocontable',
            options={'ordering': ['asiento_contable', 'linea'], 'verbose_name': 'Movimiento Contable', 'verbose_name_plural': 'Movimientos Contables'},
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='asiento_original',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asiento_reverso', to='contabilidad.asientocontable', verbose_name='Asiento Original (si es reverso)'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='comentarios',
            field=models.TextField(blank=True, verbose_name='Comentarios'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('confirmado', 'Confirmado'), ('reversado', 'Reversado'), ('procesado', 'Procesado')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='fecha_documento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Documento'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='motivo_reverso',
            field=models.TextField(blank=True, verbose_name='Motivo del Reverso'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='numero_asiento',
            field=models.CharField(default=1, max_length=20, verbose_name='Número Asiento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='periodo_contable',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.PROTECT, to='contabilidad.periodocontable', verbose_name='Período'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='usuario_creador',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Creador'),
        ),
        migrations.AddField(
            model_name='asientocontable',
            name='usuario_modificador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asientos_modificados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario Modificador'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='clasificacion_dian',
            field=models.CharField(blank=True, max_length=10, verbose_name='Clasificación DIAN'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='es_verificable',
            field=models.BooleanField(default=True, verbose_name='¿Es verificable en flujo?'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='naturaleza',
            field=models.CharField(choices=[('deudora', 'Deudora'), ('acreedora', 'Acreedora')], default='TEMP', max_length=10, verbose_name='Naturaleza'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cuenta',
            name='requiere_centro_costo',
            field=models.BooleanField(default=False, verbose_name='¿Requiere Centro de Costo?'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='requiere_proyecto',
            field=models.BooleanField(default=False, verbose_name='¿Requiere Proyecto?'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='requiere_tercero',
            field=models.BooleanField(default=False, verbose_name='¿Requiere Tercero (Cliente/Proveedor)?'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='saldo_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Saldo Máximo Permitido'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='saldo_minimo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Saldo Mínimo Permitido'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='documento_referencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Documento Referencia'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='linea',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Línea en Asiento'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='porcentaje',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Porcentaje (si aplica)'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='proyecto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='proyectos.proyecto', verbose_name='Proyecto'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='tercero',
            field=models.CharField(blank=True, max_length=100, verbose_name='Tercero (Cliente/Proveedor)'),
        ),
        migrations.AddField(
            model_name='periodocontable',
            name='permite_descuadre',
            field=models.BooleanField(default=False, verbose_name='¿Permite descuadre?'),
        ),
        migrations.AddField(
            model_name='periodocontable',
            name='usuario_cierre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario que cerró'),
        ),
        migrations.AddField(
            model_name='periodocontable',
            name='utilidad_retenida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Utilidad Retenida'),
        ),
        migrations.AlterField(
            model_name='asientocontable',
            name='tipo',
            field=models.CharField(choices=[('ingreso', 'Ingreso (Entrada de Dinero)'), ('egreso', 'Egreso (Salida de Dinero)'), ('ajuste', 'Ajuste Contable'), ('contra_asiento', 'Contra-asiento (Reverso)')], default='ingreso', max_length=20, verbose_name='Tipo de Movimiento'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='cuenta_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcuentas', to='contabilidad.cuenta', verbose_name='Cuenta Padre'),
        ),
        migrations.AlterField(
            model_name='cuenta',
            name='nivel',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='Nivel (1=Mayor, 2=Auxiliar, 3=Sub, 4=Detalle)'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['estado', 'periodo_contable'], name='contabilida_estado_e35c01_idx'),
        ),
        migrations.AddIndex(
            model_name='asientocontable',
            index=models.Index(fields=['numero_asiento'], name='contabilida_numero__33281b_idx'),
        ),
        migrations.AddIndex(
            model_name='cuenta',
            index=models.Index(fields=['codigo', 'activa'], name='contabilida_codigo_8d6208_idx'),
        ),
        migrations.AddIndex(
            model_name='cuenta',
            index=models.Index(fields=['tipo'], name='contabilida_tipo_f655f3_idx'),
        ),
        migrations.AddField(
            model_name='centrocosto',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_costo_contabilidad', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
        migrations.AddField(
            model_name='movimientocontable',
            name='centro_costo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.centrocosto', verbose_name='Centro de Costo'),
        ),
        migrations.AddIndex(
            model_name='movimientocontable',
            index=models.Index(fields=['asiento_contable', 'linea'], name='contabilida_asiento_b386ec_idx'),
        ),
        migrations.AddIndex(
            model_name='movimientocontable',
            index=models.Index(fields=['cuenta', 'centro_costo'], name='contabilida_cuenta__856c15_idx'),
        ),
        migrations.AddField(
            model_name='controlauditoria',
            name='asiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auditorias', to='contabilidad.asientocontable', verbose_name='Asiento'),
        ),
        migrations.AddField(
            model_name='controlauditoria',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddField(
            model_name='retencion',
            name='asiento_contable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contabilidad.asientocontable', verbose_name='Asiento Contable'),
        ),
        migrations.AddField(
            model_name='retencion',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='controlauditoria',
            index=models.Index(fields=['asiento', 'fecha_hora'], name='contabilida_asiento_bc6757_idx'),
        ),
        migrations.AddIndex(
            model_name='controlauditoria',
            index=models.Index(fields=['usuario', 'accion'], name='contabilida_usuario_d0eddb_idx'),
        ),
    ]
