# Generated by Django 5.2.12 on 2026-06-19 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_fix_asiento_unique'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asientocontable',
            name='numero_asiento',
            field=models.CharField(max_length=20, unique=True, verbose_name='Número Asiento'),
        ),
    ]
