# Generated by Django 5.2.12 on 2026-06-07 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(blank=True, choices=[('director', 'Director de Proyecto'), ('residente', 'Residente Técnico'), ('coordinador', 'Coordinador'), ('ingeniero', 'Ingeniero'), ('supervisor_sst', 'Supervisor SST'), ('almacenista', 'Almacenista'), ('aux_admin', 'Auxiliar Administrativo'), ('operador', 'Operador'), ('otro', 'Otro')], max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='usuarios/fotos/')),
                ('empresa', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.rol')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='PermisoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(choices=[('dashboard', 'Dashboard'), ('crm', 'CRM'), ('ventas', 'Ventas'), ('compras', 'Compras'), ('inventarios', 'Inventarios'), ('produccion', 'Producción'), ('rrhh', 'RRHH'), ('contabilidad', 'Contabilidad'), ('reportes', 'Reportes'), ('informe_diario', 'Informe Diario'), ('interventoria', 'Interventoría'), ('pos', 'Punto de Venta'), ('kave', 'KAVE Simulador'), ('configuracion', 'Configuración'), ('usuarios', 'Usuarios')], max_length=50)),
                ('nivel', models.CharField(choices=[('sin_acceso', 'Sin Acceso'), ('lectura', 'Solo Lectura'), ('operador', 'Operador'), ('admin', 'Administrador')], default='sin_acceso', max_length=20)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='usuarios.rol')),
            ],
            options={
                'verbose_name': 'Permiso de Módulo',
                'verbose_name_plural': 'Permisos de Módulos',
                'unique_together': {('rol', 'modulo')},
            },
        ),
    ]
