# Generated by Django 5.2.12 on 2026-04-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CategoriaProducto',
            new_name='Categoria',
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name': 'Categoría', 'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelTable(
            name='categoria',
            table='inventarios_categoriaproducto',
        ),
    ]
