# Generated by Django 5.2.12 on 2026-04-29 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0003_producto_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True)),
                ('responsable', models.CharField(blank=True, max_length=100)),
                ('es_principal', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'ordering': ['-es_principal', 'nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='movimientoinventario',
            options={'ordering': ['-fecha'], 'verbose_name': 'Movimiento de Inventario', 'verbose_name_plural': 'Movimientos de Inventario'},
        ),
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['nombre'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='costo_unitario',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Costo unitario al momento'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='documento_referencia',
            field=models.CharField(blank=True, help_text='Ej: OC-123, OP-456, Factura FE-789', max_length=100, verbose_name='Documento de referencia'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='origen',
            field=models.CharField(choices=[('manual', 'Manual'), ('compra', 'Orden de Compra'), ('venta', 'Venta / POS'), ('produccion', 'Orden de Producción'), ('ajuste', 'Ajuste de Inventario'), ('transferencia', 'Transferencia entre Almacenes'), ('devolucion', 'Devolución'), ('mrp', 'MRP')], default='manual', max_length=20, verbose_name='Origen del movimiento'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='stock_resultante',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Stock después del movimiento'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='usuario',
            field=models.CharField(blank=True, max_length=100, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='producto',
            name='dias_vida_util',
            field=models.PositiveIntegerField(blank=True, help_text='Para productos perecederos (ej: panadería)', null=True, verbose_name='Días de vida útil'),
        ),
        migrations.AddField(
            model_name='producto',
            name='es_perecedero',
            field=models.BooleanField(default=False, verbose_name='¿Es perecedero?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas internas'),
        ),
        migrations.AddField(
            model_name='producto',
            name='peso_unitario_kg',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Peso unitario (kg)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='punto_reorden',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cantidad en la que se debe generar una nueva orden de compra', max_digits=12, null=True, verbose_name='Punto de reorden'),
        ),
        migrations.AddField(
            model_name='producto',
            name='referencia_fabrica',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia de fábrica'),
        ),
        migrations.AddField(
            model_name='producto',
            name='requiere_lote',
            field=models.BooleanField(default=False, verbose_name='¿Requiere control de lote?'),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_maximo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Stock máximo'),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_producto',
            field=models.CharField(choices=[('materia_prima', 'Materia Prima'), ('producto_terminado', 'Producto Terminado'), ('semielaborado', 'Semielaborado'), ('insumo', 'Insumo / Consumible'), ('servicio', 'Servicio'), ('empaque', 'Empaque / Embalaje')], default='producto_terminado', max_length=20, verbose_name='Tipo de producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='ubicacion_almacen',
            field=models.CharField(blank=True, help_text='Ej: Pasillo A, Rack 3, Nivel 2', max_length=50, verbose_name='Ubicación (rack/pasillo)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad_medida',
            field=models.CharField(choices=[('UN', 'Unidad'), ('KG', 'Kilogramo'), ('G', 'Gramo'), ('LB', 'Libra'), ('LT', 'Litro'), ('ML', 'Mililitro'), ('MT', 'Metro'), ('CM', 'Centímetro'), ('M2', 'Metro cuadrado'), ('M3', 'Metro cúbico'), ('GL', 'Galón'), ('ROL', 'Rollo'), ('PAQ', 'Paquete'), ('CJ', 'Caja'), ('PLG', 'Pulgada')], default='UN', max_length=5, verbose_name='Unidad de medida'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='inventarios.producto'),
        ),
        migrations.AlterField(
            model_name='movimientoinventario',
            name='tipo',
            field=models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste_positivo', 'Ajuste Positivo'), ('ajuste_negativo', 'Ajuste Negativo'), ('transferencia_entrada', 'Transferencia Entrada'), ('transferencia_salida', 'Transferencia Salida'), ('devolucion', 'Devolución'), ('merma', 'Merma / Desperdicio'), ('produccion', 'Salida por Producción'), ('producto_terminado', 'Entrada por Producción')], max_length=25),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventarios.categoria'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='producto',
            name='stock_minimo',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=12),
        ),
        migrations.CreateModel(
            name='AlertaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('stock_bajo', 'Stock Bajo'), ('stock_agotado', 'Stock Agotado'), ('lote_por_vencer', 'Lote Próximo a Vencer'), ('lote_vencido', 'Lote Vencido'), ('sobrestock', 'Sobrestock'), ('punto_reorden', 'Punto de Reorden Alcanzado')], max_length=20)),
                ('mensaje', models.TextField()),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('vista', 'Vista'), ('resuelta', 'Resuelta'), ('ignorada', 'Ignorada')], default='activa', max_length=10)),
                ('stock_al_momento', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventarios.producto')),
            ],
            options={
                'verbose_name': 'Alerta de Inventario',
                'verbose_name_plural': 'Alertas de Inventario',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventarios.almacen', verbose_name='Almacén'),
        ),
        migrations.AddField(
            model_name='producto',
            name='almacen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='inventarios.almacen', verbose_name='Almacén principal'),
        ),
        migrations.CreateModel(
            name='ConteoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del conteo')),
                ('tipo', models.CharField(choices=[('ciclico', 'Conteo Cíclico'), ('general', 'Inventario General'), ('selectivo', 'Selectivo')], default='ciclico', max_length=15)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('aprobado', 'Aprobado')], default='pendiente', max_length=15)),
                ('responsable', models.CharField(blank=True, max_length=100)),
                ('fecha_programada', models.DateField()),
                ('fecha_ejecucion', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conteos', to='inventarios.almacen')),
            ],
            options={
                'verbose_name': 'Conteo Físico',
                'verbose_name_plural': 'Conteos Físicos',
                'ordering': ['-fecha_programada'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_lote', models.CharField(max_length=50, unique=True, verbose_name='Número de lote')),
                ('fecha_fabricacion', models.DateField(blank=True, null=True, verbose_name='Fecha de fabricación')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de vencimiento')),
                ('cantidad_inicial', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad inicial')),
                ('cantidad_disponible', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad disponible')),
                ('proveedor_origen', models.CharField(blank=True, max_length=200, verbose_name='Proveedor de origen')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('cuarentena', 'En cuarentena'), ('vencido', 'Vencido'), ('agotado', 'Agotado')], default='disponible', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='inventarios.producto')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['fecha_vencimiento', 'numero_lote'],
            },
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='lote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos', to='inventarios.lote', verbose_name='Lote'),
        ),
        migrations.CreateModel(
            name='DetalleConteoFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_sistema', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Stock en sistema')),
                ('stock_contado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Stock contado')),
                ('diferencia', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Diferencia')),
                ('ajustado', models.BooleanField(default=False, verbose_name='¿Ajuste aplicado?')),
                ('notas', models.TextField(blank=True)),
                ('conteo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventarios.conteofisico')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventarios.producto')),
            ],
            options={
                'verbose_name': 'Detalle de Conteo',
                'verbose_name_plural': 'Detalles de Conteo',
                'unique_together': {('conteo', 'producto')},
            },
        ),
    ]
