# Generated by Django 5.2.12 on 2026-05-09 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventarios", "0005_unidadmedida_alter_producto_unidad_medida"),
    ]

    operations = [
        migrations.AddField(
            model_name="movimientoinventario",
            name="descripcion",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Detalle adicional del movimiento (ej: número de venta, observaciones)",
                verbose_name="Descripción",
            ),
        ),
        migrations.AlterField(
            model_name="movimientoinventario",
            name="motivo",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
