# Generated by Django 5.2.12 on 2026-04-21 17:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facturacion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SesionCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monto_final_contado', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('monto_final_sistema', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('cerrada', 'Cerrada')], default='abierta', max_length=10)),
                ('notas', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VentaPOS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia/Billetera Digital')], default='efectivo', max_length=20)),
                ('monto_recibido', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cambio', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('factura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='venta_pos', to='facturacion.factura')),
                ('sesion_caja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='pos.sesioncaja')),
            ],
        ),
    ]
