# Generated by Django 5.2.12 on 2026-04-02 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('mantenimiento', 'En Mantenimiento')], default='activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='OrdenMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('inspección', 'Inspección')], default='preventivo', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creación', models.DateField(auto_now_add=True)),
                ('fecha_programada', models.DateField()),
                ('fecha_ejecución', models.DateField(blank=True, null=True)),
                ('horas_estimadas', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('horas_reales', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('costo_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('costo_real', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado', models.CharField(choices=[('planificada', 'Planificada'), ('en_ejecución', 'En ejecución'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='planificada', max_length=20)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('crítica', 'Crítica')], default='media', max_length=20)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes_mantenimiento', to='mantenimiento.equipo')),
                ('técnico_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordenes_mantenimiento', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Repuesto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('cantidad_disponible', models.IntegerField(default=0)),
                ('cantidad_mínima', models.IntegerField(default=1)),
                ('costo_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repuestos', to='mantenimiento.equipo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleMantenimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripción_trabajo', models.CharField(max_length=255)),
                ('cantidad_usada', models.IntegerField(default=1)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='mantenimiento.ordenmantenimiento')),
                ('repuesto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mantenimiento.repuesto')),
            ],
        ),
    ]
