# Generated by Django 5.2.12 on 2026-04-25 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformeDiarioProy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('obra', models.CharField(default='Ampliación SE LA LOMA 500 kV', max_length=200)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('codigo_formato', models.CharField(default='F-141-IN', max_length=20)),
                ('version', models.CharField(default='1', max_length=10)),
                ('mod', models.CharField(default='00', max_length=10)),
                ('lluvia', models.CharField(choices=[('SI', 'SI'), ('NO', 'NO')], default='NO', max_length=5)),
                ('he_lluvia', models.IntegerField(default=0, help_text='Horas de lluvia')),
                ('maquinaria', models.JSONField(blank=True, default=dict)),
                ('personal', models.JSONField(blank=True, default=dict)),
                ('act_administrativas', models.TextField(blank=True)),
                ('act_tecnicas_cableado', models.TextField(blank=True)),
                ('act_montaje_pruebas', models.TextField(blank=True)),
                ('act_obra_civil', models.TextField(blank=True)),
                ('act_sst_ambiental', models.TextField(blank=True)),
                ('elaborado_por', models.CharField(blank=True, max_length=200)),
                ('revisado_por', models.CharField(blank=True, max_length=200)),
                ('aprobado_por', models.CharField(blank=True, max_length=200)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='informes_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Informe Diario de Proyecto',
                'verbose_name_plural': 'Informes Diarios de Proyecto',
                'ordering': ['-fecha', '-fecha_creacion'],
            },
        ),
    ]
