# Generated by Django 5.2.12 on 2026-04-27 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operaciones", "0002_informediarioproy"),
    ]

    operations = [
        migrations.RenameField(
            model_name="informediarioproy",
            old_name="act_sst_ambiental",
            new_name="act_ambiental",
        ),
        migrations.AddField(
            model_name="informediarioproy",
            name="act_sst",
            field=models.TextField(blank=True),
        ),
    ]
