# Generated by Django 5.2.12 on 2026-03-14 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_estimado_horas', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('costo_adicional_fijo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('instrucciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('producto_terminado', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='inventarios.producto')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_a_producir', models.IntegerField(default=1)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin_estimada', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('planeada', 'Planeada'), ('en_proceso', 'En Proceso'), ('terminada', 'Terminada'), ('cancelada', 'Cancelada')], default='planeada', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='produccion.receta')),
            ],
        ),
        migrations.CreateModel(
            name='InsumoReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto_materia_prima', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='inventarios.producto')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insumos', to='produccion.receta')),
            ],
        ),
    ]
