# Generated by Django 5.2.12 on 2026-04-02 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costo_materias_primas', models.DecimalField(decimal_places=2, max_digits=14)),
                ('costo_mano_obra', models.DecimalField(decimal_places=2, max_digits=14)),
                ('costo_indirecto', models.DecimalField(decimal_places=2, max_digits=14)),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=14)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('orden', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costo', to='produccion.ordenproduccion')),
            ],
        ),
    ]
