# Generated by Django 5.2.12 on 2026-04-04 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0002_auditoria_evaluacionproveedor_documentoiso_and_more'),
        ('produccion', '0002_costoproduccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='receta',
            name='instructivos_sgc',
            field=models.ManyToManyField(blank=True, limit_choices_to={'categoria': '3_instructivo'}, to='calidad.documentoiso', verbose_name='Instructivos SGC (ISO 9001)'),
        ),
    ]
