# Generated by Django 5.2.12 on 2026-04-29 17:29

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0004_almacen_alter_movimientoinventario_options_and_more'),
        ('produccion', '0003_receta_instructivos_sgc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costoproduccion',
            options={'verbose_name': 'Costo de Producción', 'verbose_name_plural': 'Costos de Producción'},
        ),
        migrations.AlterModelOptions(
            name='insumoreceta',
            options={'verbose_name': 'Insumo de Receta', 'verbose_name_plural': 'Insumos de Receta'},
        ),
        migrations.AlterModelOptions(
            name='ordenproduccion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Orden de Producción', 'verbose_name_plural': 'Órdenes de Producción'},
        ),
        migrations.AlterModelOptions(
            name='receta',
            options={'verbose_name': 'Receta de Producción', 'verbose_name_plural': 'Recetas de Producción'},
        ),
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='fecha_fin_estimada',
        ),
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='fecha_inicio',
        ),
        migrations.AddField(
            model_name='costoproduccion',
            name='costo_mermas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='costoproduccion',
            name='costo_unitario_real',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AddField(
            model_name='insumoreceta',
            name='merma_esperada_pct',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje adicional que normalmente se pierde', max_digits=5, verbose_name='Merma esperada (%)'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='cantidad_producida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Cantidad real producida'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_fin_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fin real'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_inicio_real',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Inicio real'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_planeada_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha planeada de fin'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='fecha_planeada_inicio',
            field=models.DateField(default=datetime.date(2026, 4, 29), verbose_name='Fecha planeada de inicio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='notas_calidad',
            field=models.TextField(blank=True, help_text='Anotaciones de inspección final'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='numero',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Número de OP'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='responsable',
            field=models.CharField(blank=True, max_length=100, verbose_name='Responsable de la OP'),
        ),
        migrations.AddField(
            model_name='receta',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='costoproduccion',
            name='costo_indirecto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='costoproduccion',
            name='costo_mano_obra',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='costoproduccion',
            name='costo_materias_primas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='costoproduccion',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='insumoreceta',
            name='cantidad_requerida',
            field=models.DecimalField(decimal_places=4, max_digits=12, verbose_name='Cantidad requerida base'),
        ),
        migrations.AlterField(
            model_name='insumoreceta',
            name='producto_materia_prima',
            field=models.ForeignKey(limit_choices_to={'tipo_producto__in': ['materia_prima', 'insumo', 'empaque']}, on_delete=django.db.models.deletion.RESTRICT, to='inventarios.producto', verbose_name='Materia Prima / Insumo'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='cantidad_a_producir',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad a producir'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('planeada', 'Planeada (Lista para iniciar)'), ('en_proceso', 'En Proceso'), ('pausada', 'Pausada'), ('terminada', 'Terminada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='receta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='produccion.receta', verbose_name='Receta a producir'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='costo_adicional_fijo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Costos indirectos de fabricación fijos por unidad', max_digits=12, verbose_name='Costo fijo adicional'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='instrucciones',
            field=models.TextField(blank=True, default='', verbose_name='Instrucciones de producción'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receta',
            name='producto_terminado',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receta', to='inventarios.producto', verbose_name='Producto Terminado'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='tiempo_estimado_horas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Tiempo estimado (horas)'),
        ),
        migrations.AlterUniqueTogether(
            name='insumoreceta',
            unique_together={('receta', 'producto_materia_prima')},
        ),
        migrations.CreateModel(
            name='ConsumoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_consumida', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fecha_consumo', models.DateTimeField(default=django.utils.timezone.now)),
                ('registrado_por', models.CharField(blank=True, max_length=100)),
                ('movimiento_inventario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumo_produccion', to='inventarios.movimientoinventario')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumos', to='produccion.ordenproduccion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventarios.producto')),
            ],
            options={
                'verbose_name': 'Consumo de Producción',
                'verbose_name_plural': 'Consumos de Producción',
            },
        ),
        migrations.CreateModel(
            name='FaseOrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_fase', models.CharField(max_length=100, verbose_name='Nombre de la fase (ej: Bobinado)')),
                ('secuencia', models.PositiveIntegerField(default=1)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En Proceso'), ('terminada', 'Terminada')], default='pendiente', max_length=20)),
                ('operario', models.CharField(blank=True, max_length=100, verbose_name='Operario asignado')),
                ('horas_estimadas', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('horas_reales', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('inicio_fase', models.DateTimeField(blank=True, null=True)),
                ('fin_fase', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fases', to='produccion.ordenproduccion')),
            ],
            options={
                'verbose_name': 'Fase de Orden',
                'verbose_name_plural': 'Fases de Orden',
                'ordering': ['orden', 'secuencia'],
            },
        ),
        migrations.CreateModel(
            name='MermaProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=4, max_digits=10)),
                ('motivo', models.CharField(max_length=200, verbose_name='Motivo de la merma')),
                ('es_recuperable', models.BooleanField(default=False, verbose_name='¿Es reciclable/recuperable?')),
                ('fecha_registro', models.DateTimeField(default=django.utils.timezone.now)),
                ('movimiento_inventario', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merma_produccion', to='inventarios.movimientoinventario')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mermas', to='produccion.ordenproduccion')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventarios.producto')),
            ],
            options={
                'verbose_name': 'Merma de Producción',
                'verbose_name_plural': 'Mermas de Producción',
            },
        ),
    ]
