# Generated by Django 5.2.12 on 2026-03-29 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_cotizaciondetalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='representante',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
