# Generated by Django 5.2.12 on 2026-03-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_cliente_representante'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='gran_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=19.0, max_digits=5),
        ),
    ]
