# Generated by Django 5.2.12 on 2026-03-29 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_cotizacion_gran_total_cotizacion_numero_cotizacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cotizacion',
            name='forma_pago',
            field=models.CharField(blank=True, default='Contado', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='garantia',
            field=models.CharField(blank=True, default='1 Año', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='tiempo_entrega',
            field=models.CharField(blank=True, default='15 días hábiles', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='cotizacion',
            name='validez_oferta',
            field=models.CharField(blank=True, default='30 Días', max_length=200, null=True),
        ),
    ]
