# Generated by Django 5.2.12 on 2026-04-27 17:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0007_cotizacion_forma_pago_cotizacion_garantia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El número debe tener formato: '+999999999'. De 9 a 15 dígitos.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
