# Generated by Django 5.2.12 on 2026-05-06 15:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0008_alter_cliente_telefono"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cliente",
            name="representante",
        ),
        migrations.AddField(
            model_name="cliente",
            name="adjunto_archivos",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="crm/adjuntos/",
                verbose_name="Adjuntos",
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="compania",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Compañía"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="nit",
            field=models.CharField(
                blank=True, max_length=20, null=True, unique=True, verbose_name="NIT"
            ),
        ),
        migrations.AddField(
            model_name="cliente",
            name="notas",
            field=models.TextField(blank=True, null=True, verbose_name="Notas"),
        ),
        migrations.AlterField(
            model_name="cliente",
            name="telefono",
            field=models.CharField(
                blank=True,
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="El número debe tener entre 7 y 20 dígitos (puede incluir espacios o guiones).",
                        regex="^\\+?[\\d\\s\\-]{7,20}$",
                    )
                ],
            ),
        ),
    ]
