# Generated by Django 5.2.12 on 2026-05-16 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_remove_cliente_representante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='logotipo',
            field=models.ImageField(blank=True, null=True, upload_to='crm/logotipos/', verbose_name='Logotipo de la Empresa'),
        ),
    ]
