# Generated by Django 5.2.12 on 2026-05-16 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0010_cliente_logotipo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AddField(
            model_name='cliente',
            name='agente_retenedor',
            field=models.BooleanField(default=False, verbose_name='¿Agente Retenedor?'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='banco_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cargo_contacto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo Contacto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cedula_representante',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula Representante'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ciudad_entrega',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad Entrega'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='clasificacion',
            field=models.CharField(choices=[('A', 'Clase A - Premium'), ('B', 'Clase B - Estándar'), ('C', 'Clase C - Básico')], default='B', max_length=1, verbose_name='Clasificación'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_bancario',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Bancario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Barras'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_cliente',
            field=models.CharField(default='LEGACY', max_length=50, unique=True, verbose_name='Código Cliente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='condicion_pago',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Condición de Pago'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='contacto_principal',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Contacto Principal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='credito_maximo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Crédito Máximo (COP)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='descuento_general',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento General (%)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='dias_credito',
            field=models.PositiveIntegerField(default=0, verbose_name='Días de Crédito'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='digito_verificacion',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Dígito Verificación'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='direccion_entrega',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección de Entrega'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email_contacto',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Contacto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('suspendido', 'Suspendido'), ('bloqueado', 'Bloqueado')], default='activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Actualización'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_constitucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Constitución'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_resolucion_dian',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Resolución DIAN'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_ultimo_contacto',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Último Contacto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='gran_contribuyente',
            field=models.BooleanField(default=False, verbose_name='¿Gran Contribuyente?'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='lista_precios',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lista de Precios'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Cuenta'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='numero_resolucion_dian',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Resolución DIAN'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='pais',
            field=models.CharField(default='Colombia', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='regimen_tributario',
            field=models.CharField(choices=[('comun', 'Régimen Común'), ('simplificado', 'Régimen Simplificado'), ('especial', 'Régimen Especial')], default='comun', max_length=20, verbose_name='Régimen Tributario'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='representante_legal',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Representante Legal'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='responsable_iva',
            field=models.BooleanField(default=False, verbose_name='¿Responsable de IVA?'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='sector_industria',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sector/Industria'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_alterno',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Alterno'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='telefono_contacto',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Contacto'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cliente',
            field=models.CharField(choices=[('persona_natural', 'Persona Natural'), ('empresa', 'Empresa'), ('empresa_unipersonal', 'Empresa Unipersonal'), ('cooperativa', 'Cooperativa')], default='empresa', max_length=25, verbose_name='Tipo de Cliente'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('corriente', 'Cuenta Corriente'), ('ahorros', 'Cuenta de Ahorros'), ('nomina', 'Cuenta Nómina')], max_length=20, null=True, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='titular_cuenta',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titular Cuenta'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cédula'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(verbose_name='Dirección de Facturación'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=200, verbose_name='Nombre/Razón Social'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='notas',
            field=models.TextField(blank=True, null=True, verbose_name='Notas Internas'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono Principal'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['nit'], name='crm_cliente_nit_2f492d_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['codigo_cliente'], name='crm_cliente_codigo__6efc96_idx'),
        ),
        migrations.AddIndex(
            model_name='cliente',
            index=models.Index(fields=['estado'], name='crm_cliente_estado_b7da3f_idx'),
        ),
    ]
