# Generated by Django 5.2.12 on 2026-05-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_alter_cliente_options_cliente_agente_retenedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='actividad_economica_ciiu',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Actividad Económica (CIIU)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo_facturacion_electronica',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo para Facturación Electrónica'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='matricula_mercantil',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula Mercantil'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='responsabilidades_fiscales',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsabilidades Fiscales (DIAN)'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.CharField(choices=[('NIT', 'NIT'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte')], default='NIT', max_length=5, verbose_name='Tipo de Documento'),
        ),
    ]
