# Generated by Django 5.2.12 on 2026-06-07 22:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0012_cliente_actividad_economica_ciiu_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cotizacion',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Cotización', 'verbose_name_plural': 'Cotizaciones'},
        ),
        migrations.AlterModelOptions(
            name='cotizaciondetalle',
            options={'ordering': ['item'], 'verbose_name': 'Detalle de Cotización', 'verbose_name_plural': 'Detalles de Cotización'},
        ),
        migrations.AlterModelOptions(
            name='oportunidad',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Oportunidad', 'verbose_name_plural': 'Oportunidades'},
        ),
        migrations.AddField(
            model_name='oportunidad',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='codigo_cliente',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código Cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='asunto',
            field=models.CharField(max_length=200, verbose_name='Asunto'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotizaciones', to='crm.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('facturada', 'Facturada')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='fecha_validez',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Validez'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='forma_pago',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Forma de Pago'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='garantia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Garantía'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='gran_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Gran Total'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='numero_cotizacion',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='N° Cotización'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='% IVA'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='tiempo_entrega',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tiempo de Entrega'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='validez_oferta',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Validez de Oferta'),
        ),
        migrations.AlterField(
            model_name='cotizacion',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Subtotal'),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='cotizacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='crm.cotizacion', verbose_name='Cotización'),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='item',
            field=models.IntegerField(verbose_name='Ítem'),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='producto',
            field=models.CharField(max_length=200, verbose_name='Producto/Servicio'),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='unidad',
            field=models.CharField(default='UND', max_length=50, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Total'),
        ),
        migrations.AlterField(
            model_name='cotizaciondetalle',
            name='valor_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Valor Unitario'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oportunidades', to='crm.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('calificado', 'Calificado'), ('propuesta', 'Propuesta'), ('negociacion', 'Negociación'), ('ganado', 'Ganado'), ('perdido', 'Perdido')], default='nuevo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='oportunidad',
            name='valor_estimado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Valor Estimado'),
        ),
    ]
