# Generated by Django 5.2.12 on 2026-04-02 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0007_cotizacion_forma_pago_cotizacion_garantia_and_more'),
        ('inventarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('origen', models.CharField(max_length=200)),
                ('destino', models.CharField(max_length=200)),
                ('distancia_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tiempo_estimado_horas', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=20, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('capacidad', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_ruta', 'En Ruta'), ('mantenimiento', 'En Mantenimiento'), ('fuera_servicio', 'Fuera de Servicio')], default='disponible', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_envio', models.CharField(max_length=50, unique=True)),
                ('fecha_envio', models.DateTimeField(auto_now_add=True)),
                ('fecha_entrega_estimada', models.DateTimeField(blank=True, null=True)),
                ('fecha_entrega_real', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('preparando', 'Preparando'), ('en_transito', 'En Tránsito'), ('entregado', 'Entregado'), ('retrasado', 'Retrasado'), ('cancelado', 'Cancelado')], default='preparando', max_length=20)),
                ('peso_total', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('costo_envio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm.cliente')),
                ('ruta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistica.ruta')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistica.vehiculo')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('peso_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventarios.producto')),
                ('envio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='logistica.envio')),
            ],
        ),
    ]
