# Generated by Django 5.2.12 on 2026-05-17 15:46

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventarios', '0006_movimientoinventario_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grupo de Material',
                'verbose_name_plural': 'Grupos de Material',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='TipoEmpaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Tipo de Empaque',
                'verbose_name_plural': 'Tipos de Empaque',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='FamiliaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subfamilias', to='productos.familiaproducto')),
            ],
            options={
                'verbose_name': 'Familia de Producto',
                'verbose_name_plural': 'Familias de Producto',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='FichaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_interno', models.CharField(blank=True, max_length=50, verbose_name='Código interno')),
                ('codigo_dian', models.CharField(blank=True, max_length=50, verbose_name='Código DIAN / FE')),
                ('codigo_arancelario', models.CharField(blank=True, max_length=20, verbose_name='Partida arancelaria (HS)')),
                ('codigo_gtin', models.CharField(blank=True, max_length=14, verbose_name='GTIN / EAN principal')),
                ('presentacion', models.CharField(blank=True, help_text='Ej: Caja x 12 unidades', max_length=200)),
                ('contenido_neto', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Contenido neto')),
                ('unidad_contenido', models.CharField(blank=True, max_length=30, verbose_name='UM contenido')),
                ('unidades_por_empaque', models.PositiveIntegerField(blank=True, null=True, verbose_name='Unidades por empaque')),
                ('largo_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ancho_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alto_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('volumen_m3', models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True)),
                ('peso_bruto_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('peso_neto_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('pais_origen', models.CharField(blank=True, default='Colombia', max_length=80)),
                ('fabricante', models.CharField(blank=True, max_length=200)),
                ('proveedor_habitual', models.CharField(blank=True, max_length=200)),
                ('lead_time_dias', models.PositiveIntegerField(blank=True, null=True, verbose_name='Lead time (días)')),
                ('cantidad_minima_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='MOQ compra')),
                ('moneda_compra', models.CharField(blank=True, default='COP', max_length=3)),
                ('ultimo_precio_compra', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('fecha_ultima_compra', models.DateField(blank=True, null=True)),
                ('lista_precios', models.CharField(blank=True, default='General', max_length=50)),
                ('iva_porcentaje', models.DecimalField(decimal_places=2, default=19, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('precio_sugerido', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('permite_descuento', models.BooleanField(default=True)),
                ('es_vendible', models.BooleanField(default=True)),
                ('politica_inventario', models.CharField(choices=[('lote_por_lote', 'Lote por lote'), ('punto_reorden', 'Punto de reorden'), ('planificacion', 'Planificación MRP'), ('sin_planificacion', 'Sin planificación')], default='punto_reorden', max_length=20)),
                ('planificador', models.CharField(blank=True, max_length=100)),
                ('tiempo_produccion_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('lote_minimo_produccion', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('lote_estandar', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('gestion_lote', models.BooleanField(default=False)),
                ('gestion_serie', models.BooleanField(default=False)),
                ('temperatura_almacenamiento', models.CharField(blank=True, max_length=100)),
                ('clase_abc', models.CharField(blank=True, choices=[('A', 'Clase A — Alto valor/rotación'), ('B', 'Clase B — Medio'), ('C', 'Clase C — Bajo')], max_length=1)),
                ('estado_material', models.CharField(choices=[('activo', 'Activo'), ('bloqueado', 'Bloqueado'), ('obsoleto', 'Obsoleto'), ('en_desarrollo', 'En desarrollo')], default='activo', max_length=15)),
                ('requiere_certificado', models.BooleanField(default=False)),
                ('norma_calidad', models.CharField(blank=True, max_length=100)),
                ('ficha_tecnica_url', models.URLField(blank=True)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('familia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.familiaproducto')),
                ('producto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='inventarios.producto')),
                ('grupo_material', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.grupomaterial')),
                ('tipo_empaque', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='productos.tipoempaque')),
            ],
            options={
                'verbose_name': 'Ficha de Producto',
                'verbose_name_plural': 'Fichas de Producto',
            },
        ),
        migrations.CreateModel(
            name='UnidadEmpaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.CharField(choices=[('unidad', 'Unidad base'), ('inner', 'Empaque interno'), ('caja', 'Caja / Cartón'), ('bulto', 'Bulto'), ('pallet', 'Pallet / Estiba'), ('contenedor', 'Contenedor')], default='caja', max_length=15)),
                ('codigo', models.CharField(blank=True, max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
                ('factor_conversion', models.DecimalField(decimal_places=4, help_text='Cuántas unidades base contiene este empaque', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)])),
                ('codigo_barras', models.CharField(blank=True, max_length=50)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('largo_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ancho_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alto_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('es_predeterminado', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_empaque', to='inventarios.producto')),
            ],
            options={
                'verbose_name': 'Unidad de Empaque',
                'verbose_name_plural': 'Unidades de Empaque',
                'ordering': ['factor_conversion'],
            },
        ),
        migrations.CreateModel(
            name='CodigoBarras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('EAN13', 'EAN-13'), ('EAN8', 'EAN-8'), ('UPC', 'UPC-A'), ('CODE128', 'Code 128'), ('CODE39', 'Code 39'), ('QR', 'QR'), ('INTERNO', 'Código interno'), ('GTIN14', 'GTIN-14 (caja)')], default='EAN13', max_length=10)),
                ('es_principal', models.BooleanField(default=False)),
                ('descripcion', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='codigos_barras', to='inventarios.producto')),
            ],
            options={
                'verbose_name': 'Código de Barras',
                'verbose_name_plural': 'Códigos de Barras',
                'ordering': ['-es_principal', 'tipo'],
                'unique_together': {('producto', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='UnidadMedidaAlternativa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factor_a_base', models.DecimalField(decimal_places=6, help_text='1 [esta UM] = X unidades base', max_digits=12, validators=[django.core.validators.MinValueValidator(1e-06)])),
                ('codigo_barras', models.CharField(blank=True, max_length=50)),
                ('es_predeterminada_venta', models.BooleanField(default=False)),
                ('es_predeterminada_compra', models.BooleanField(default=False)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades_alternativas', to='inventarios.producto')),
                ('unidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='conversiones_producto', to='inventarios.unidadmedida')),
            ],
            options={
                'verbose_name': 'Unidad de Medida Alternativa',
                'verbose_name_plural': 'Unidades de Medida Alternativas',
                'unique_together': {('producto', 'unidad')},
            },
        ),
    ]
