# Generated by Django 5.2.12 on 2026-06-19 17:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='codigobarras',
            options={'ordering': ['-es_principal', 'tipo'], 'verbose_name': 'Codigo de Barras', 'verbose_name_plural': 'Codigos de Barras'},
        ),
        migrations.AddField(
            model_name='fichaproducto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/imagenes/', verbose_name='Imagen del Producto'),
        ),
        migrations.AlterField(
            model_name='codigobarras',
            name='tipo',
            field=models.CharField(choices=[('EAN13', 'EAN-13'), ('EAN8', 'EAN-8'), ('UPC', 'UPC-A'), ('CODE128', 'Code 128'), ('CODE39', 'Code 39'), ('QR', 'QR'), ('INTERNO', 'Codigo interno'), ('GTIN14', 'GTIN-14 (caja)')], default='EAN13', max_length=10),
        ),
        migrations.AlterField(
            model_name='fichaproducto',
            name='clase_abc',
            field=models.CharField(blank=True, choices=[('A', 'Clase A — Alto valor/rotacion'), ('B', 'Clase B — Medio'), ('C', 'Clase C — Bajo')], max_length=1),
        ),
        migrations.AlterField(
            model_name='fichaproducto',
            name='codigo_dian',
            field=models.CharField(blank=True, max_length=50, verbose_name='Codigo DIAN / FE'),
        ),
        migrations.AlterField(
            model_name='fichaproducto',
            name='codigo_interno',
            field=models.CharField(blank=True, max_length=50, verbose_name='Codigo interno'),
        ),
        migrations.AlterField(
            model_name='fichaproducto',
            name='lead_time_dias',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Lead time (dias)'),
        ),
        migrations.AlterField(
            model_name='fichaproducto',
            name='politica_inventario',
            field=models.CharField(choices=[('lote_por_lote', 'Lote por lote'), ('punto_reorden', 'Punto de reorden'), ('planificacion', 'Planificacion MRP'), ('sin_planificacion', 'Sin planificacion')], default='punto_reorden', max_length=20),
        ),
        migrations.AlterField(
            model_name='unidadempaque',
            name='factor_conversion',
            field=models.DecimalField(decimal_places=4, help_text='Cuantas unidades base contiene este empaque', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0001)]),
        ),
        migrations.AlterField(
            model_name='unidadempaque',
            name='nivel',
            field=models.CharField(choices=[('unidad', 'Unidad base'), ('inner', 'Empaque interno'), ('caja', 'Caja / Carton'), ('bulto', 'Bulto'), ('pallet', 'Pallet / Estiba'), ('contenedor', 'Contenedor')], default='caja', max_length=15),
        ),
    ]
