# Generated by Django 5.2.12 on 2026-04-02 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='cobro_contabilizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facturaventa',
            name='contabilidad_generado',
            field=models.BooleanField(default=False),
        ),
    ]
