# Generated by Django 5.2.12 on 2026-05-02 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0002_facturaventa_cobro_contabilizado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaventa',
            name='inventario_descontado',
            field=models.BooleanField(default=False, verbose_name='¿Stock descontado?'),
        ),
    ]
