# Generated by Django 5.2.12 on 2026-05-04 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venta', '0003_facturaventa_inventario_descontado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturaventa',
            name='orden_venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='venta.ordenventa'),
        ),
    ]
