# Generated by Django 5.2.12 on 2026-05-04 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventarios', '0004_almacen_alter_movimientoinventario_options_and_more'),
        ('venta', '0004_allow_multiple_invoices_per_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_nota', models.CharField(max_length=50, unique=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('devolucion', 'Devolución de Mercancía'), ('descuento', 'Descuento/Anulación'), ('correccion', 'Corrección de Factura')], default='devolucion', max_length=20)),
                ('motivo', models.TextField(verbose_name='Motivo de la nota de crédito')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='% IVA')),
                ('valor_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada a DIAN'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='borrador', max_length=20)),
                ('cufe', models.CharField(blank=True, max_length=100, verbose_name='CUFE DIAN')),
                ('contabilidad_generado', models.BooleanField(default=False)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito', to='venta.facturaventa')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='DetalleNotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventarios.producto')),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='venta.notacredito')),
            ],
            options={
                'verbose_name': 'Detalle Nota de Crédito',
                'verbose_name_plural': 'Detalles Notas de Crédito',
            },
        ),
    ]
