# Generated by Django 5.2.12 on 2026-04-03 17:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProyectoKAVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Proyecto')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('cliente', models.CharField(max_length=200, verbose_name='Cliente')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de Inicio')),
                ('fecha_entrega', models.DateField(verbose_name='Fecha de Entrega Estimada')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10, verbose_name='Prioridad')),
                ('presupuesto', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Presupuesto')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.empresa', verbose_name='Empresa')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Responsable')),
            ],
            options={
                'verbose_name': 'Proyecto KAVE',
                'verbose_name_plural': 'Proyectos KAVE',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='NotaKAVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Nota')),
                ('contenido', models.TextField(verbose_name='Contenido')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('autor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas', to='kave.proyectokave', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Nota KAVE',
                'verbose_name_plural': 'Notas KAVE',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoKAVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título del Documento')),
                ('tipo', models.CharField(choices=[('contrato', 'Contrato'), ('cotizacion', 'Cotización'), ('factura', 'Factura'), ('informe', 'Informe'), ('plano', 'Plano'), ('especificacion', 'Especificación'), ('otro', 'Otro')], max_length=20, verbose_name='Tipo de Documento')),
                ('archivo', models.FileField(upload_to='kave/documentos/', verbose_name='Archivo')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Subida')),
                ('subido_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Subido por')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='kave.proyectokave', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Documento KAVE',
                'verbose_name_plural': 'Documentos KAVE',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='TareaKAVE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título de la Tarea')),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('completada', 'Completada'), ('bloqueada', 'Bloqueada')], default='pendiente', max_length=20, verbose_name='Estado')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Vencimiento')),
                ('horas_estimadas', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Horas Estimadas')),
                ('horas_reales', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Horas Reales')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Asignado a')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='kave.proyectokave', verbose_name='Proyecto')),
            ],
            options={
                'verbose_name': 'Tarea KAVE',
                'verbose_name_plural': 'Tareas KAVE',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='TransformerDesign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('potencia_kva', models.FloatField(verbose_name='Potencia (kVA)')),
                ('vp', models.FloatField(verbose_name='Voltaje Primario (V)')),
                ('vs', models.FloatField(verbose_name='Voltaje Secundario (V)')),
                ('tipo', models.CharField(choices=[('monofasico', 'Monofásico'), ('trifasico', 'Trifásico'), ('autotransformador', 'Autotransformador')], max_length=20, verbose_name='Tipo de Transformador')),
                ('material', models.CharField(choices=[('silicio', 'Acero al Silicio'), ('amorfoso', 'Acero Amorfo'), ('nanocristalino', 'Nanocristalino'), ('ferrita', 'Ferrita')], max_length=20, verbose_name='Material del Núcleo')),
                ('nucleo', models.CharField(max_length=50, verbose_name='Tipo de Núcleo')),
                ('eficiencia', models.FloatField(verbose_name='Eficiencia (%)')),
                ('costo', models.FloatField(verbose_name='Costo Estimado ($)')),
                ('frecuencia', models.FloatField(default=60, verbose_name='Frecuencia (Hz)')),
                ('densidad_corriente', models.FloatField(default=2.5, verbose_name='Densidad de Corriente (A/mm²)')),
                ('induccion_maxima', models.FloatField(default=1.5, verbose_name='Inducción Máxima (T)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizado en')),
                ('disenador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Diseñador')),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='kave.proyectokave', verbose_name='Proyecto Asociado')),
            ],
            options={
                'verbose_name': 'Diseño de Transformador',
                'verbose_name_plural': 'Diseños de Transformadores',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculoTransformador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_nucleo', models.FloatField(verbose_name='Área del Núcleo (cm²)')),
                ('vueltas_primario', models.IntegerField(verbose_name='Vueltas Primario')),
                ('vueltas_secundario', models.IntegerField(verbose_name='Vueltas Secundario')),
                ('area_conductor_primario', models.FloatField(verbose_name='Área Conductor Primario (mm²)')),
                ('area_conductor_secundario', models.FloatField(verbose_name='Área Conductor Secundario (mm²)')),
                ('perdidas_nucleo', models.FloatField(verbose_name='Pérdidas en Núcleo (W)')),
                ('perdidas_cobre', models.FloatField(verbose_name='Pérdidas en Cobre (W)')),
                ('perdidas_totales', models.FloatField(verbose_name='Pérdidas Totales (W)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('disenador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos', to='kave.transformerdesign')),
            ],
            options={
                'verbose_name': 'Cálculo de Transformador',
                'verbose_name_plural': 'Cálculos de Transformadores',
                'ordering': ['-created_at'],
            },
        ),
    ]
