# Generated by Django 5.2.12 on 2026-04-04 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kave', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculotransformador',
            name='alto_platina_primario',
            field=models.FloatField(blank=True, null=True, verbose_name='Alto Platina Primario (mm)'),
        ),
        migrations.AddField(
            model_name='calculotransformador',
            name='alto_platina_secundario',
            field=models.FloatField(blank=True, null=True, verbose_name='Alto Platina Secundario (mm)'),
        ),
        migrations.AddField(
            model_name='calculotransformador',
            name='altura_efectiva_bobinado',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura Bobinado Efectiva (mm)'),
        ),
        migrations.AddField(
            model_name='calculotransformador',
            name='ancho_platina_primario',
            field=models.FloatField(blank=True, null=True, verbose_name='Ancho Platina Primario (mm)'),
        ),
        migrations.AddField(
            model_name='calculotransformador',
            name='ancho_platina_secundario',
            field=models.FloatField(blank=True, null=True, verbose_name='Ancho Platina Secundario (mm)'),
        ),
        migrations.AddField(
            model_name='calculotransformador',
            name='calibre_awg_primario',
            field=models.CharField(blank=True, max_length=10, verbose_name='Calibre AWG Primario'),
        ),
        migrations.AddField(
            model_name='calculotransformador',
            name='calibre_awg_secundario',
            field=models.CharField(blank=True, max_length=10, verbose_name='Calibre AWG Secundario'),
        ),
        migrations.AddField(
            model_name='calculotransformador',
            name='espesor_total_bobinado',
            field=models.FloatField(blank=True, null=True, verbose_name='Espesor Radial Construido (mm)'),
        ),
        migrations.AddField(
            model_name='calculotransformador',
            name='factor_utilizacion_ventana',
            field=models.FloatField(blank=True, null=True, verbose_name='Ku (Factor Ventana)'),
        ),
        migrations.AddField(
            model_name='calculotransformador',
            name='mensajes_viabilidad',
            field=models.TextField(blank=True, verbose_name='Diagnóstico de Ventana'),
        ),
        migrations.AddField(
            model_name='calculotransformador',
            name='peso_cobre_estimado',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso Cobre (kg)'),
        ),
        migrations.AddField(
            model_name='calculotransformador',
            name='peso_nucleo_estimado',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso Núcleo (kg)'),
        ),
        migrations.AddField(
            model_name='calculotransformador',
            name='tipo_conductor_primario',
            field=models.CharField(choices=[('awg', 'Hilo Redondo (AWG)'), ('platina', 'Platina (Rectangular)')], default='awg', max_length=20),
        ),
        migrations.AddField(
            model_name='calculotransformador',
            name='tipo_conductor_secundario',
            field=models.CharField(choices=[('awg', 'Hilo Redondo (AWG)'), ('platina', 'Platina (Rectangular)')], default='awg', max_length=20),
        ),
        migrations.AddField(
            model_name='calculotransformador',
            name='viabilidad_construccion',
            field=models.BooleanField(default=False, verbose_name='¿Cabe en Ventana?'),
        ),
        migrations.AddField(
            model_name='transformerdesign',
            name='aislamiento_entre_devanados',
            field=models.FloatField(default=1.0, verbose_name='Aislamiento Prim/Sec (mm)'),
        ),
        migrations.AddField(
            model_name='transformerdesign',
            name='aislamiento_tubo',
            field=models.FloatField(default=2.0, verbose_name='Espesor del Tubo/Carrete (mm)'),
        ),
        migrations.AddField(
            model_name='transformerdesign',
            name='altura_toroide',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura del Toroide (mm)'),
        ),
        migrations.AddField(
            model_name='transformerdesign',
            name='altura_ventana',
            field=models.FloatField(blank=True, null=True, verbose_name='Altura de Ventana (mm)'),
        ),
        migrations.AddField(
            model_name='transformerdesign',
            name='ancho_pierna',
            field=models.FloatField(blank=True, null=True, verbose_name='Ancho de Pierna Central (mm)'),
        ),
        migrations.AddField(
            model_name='transformerdesign',
            name='ancho_ventana',
            field=models.FloatField(blank=True, null=True, verbose_name='Ancho de Ventana (mm)'),
        ),
        migrations.AddField(
            model_name='transformerdesign',
            name='canal_entre_capas',
            field=models.FloatField(default=0.1, verbose_name='Canal/Aislamiento entre capas (mm)'),
        ),
        migrations.AddField(
            model_name='transformerdesign',
            name='diametro_externo',
            field=models.FloatField(blank=True, null=True, verbose_name='Diámetro Externo Toroidal (mm)'),
        ),
        migrations.AddField(
            model_name='transformerdesign',
            name='diametro_interno',
            field=models.FloatField(blank=True, null=True, verbose_name='Diámetro Interno Toroidal (mm)'),
        ),
        migrations.AddField(
            model_name='transformerdesign',
            name='factor_apilamiento',
            field=models.FloatField(default=0.96, verbose_name='Factor de Apilamiento (Ku)'),
        ),
        migrations.AddField(
            model_name='transformerdesign',
            name='forma_nucleo',
            field=models.CharField(choices=[('ei', 'Acorazado (E-I) / Columnas'), ('toroidal', 'Toroidal')], default='ei', max_length=20, verbose_name='Forma del Núcleo'),
        ),
        migrations.AddField(
            model_name='transformerdesign',
            name='levante_bobinado',
            field=models.FloatField(default=15.0, verbose_name='Swell/Levante de Bobinado (%)'),
        ),
        migrations.AddField(
            model_name='transformerdesign',
            name='margen_seguridad_extremos',
            field=models.FloatField(default=5.0, verbose_name='Margen de seguridad extremos (mm)'),
        ),
        migrations.AddField(
            model_name='transformerdesign',
            name='profundidad_nucleo',
            field=models.FloatField(blank=True, null=True, verbose_name='Profundidad del Núcleo (mm)'),
        ),
        migrations.AddField(
            model_name='transformerdesign',
            name='refrigeracion',
            field=models.CharField(choices=[('seco', 'Seco'), ('aceite', 'En Aceite')], default='seco', max_length=20, verbose_name='Tipo de Refrigeración'),
        ),
        migrations.AlterField(
            model_name='calculotransformador',
            name='area_conductor_primario',
            field=models.FloatField(verbose_name='Área Conductor Primario Efectiva (mm²)'),
        ),
        migrations.AlterField(
            model_name='calculotransformador',
            name='area_conductor_secundario',
            field=models.FloatField(verbose_name='Área Conductor Secundario Efectiva (mm²)'),
        ),
        migrations.AlterField(
            model_name='calculotransformador',
            name='area_nucleo',
            field=models.FloatField(verbose_name='Área Eléctrica Teórica (cm²)'),
        ),
        migrations.AlterField(
            model_name='calculotransformador',
            name='perdidas_cobre',
            field=models.FloatField(verbose_name='Pérdidas en Cobre (W) - Pcu'),
        ),
        migrations.AlterField(
            model_name='calculotransformador',
            name='perdidas_nucleo',
            field=models.FloatField(verbose_name='Pérdidas en Núcleo (W) - P0'),
        ),
        migrations.AlterField(
            model_name='transformerdesign',
            name='costo',
            field=models.FloatField(blank=True, null=True, verbose_name='Costo Estimado ($)'),
        ),
        migrations.AlterField(
            model_name='transformerdesign',
            name='eficiencia',
            field=models.FloatField(default=98.0, verbose_name='Eficiencia Esperada (%)'),
        ),
        migrations.AlterField(
            model_name='transformerdesign',
            name='material',
            field=models.CharField(choices=[('silicio', 'Acero al Silicio M-4/M-5 Gobernado'), ('amorfoso', 'Acero Amorfo'), ('nanocristalino', 'Nanocristalino'), ('ferrita', 'Ferrita')], max_length=40, verbose_name='Material del Núcleo'),
        ),
        migrations.AlterField(
            model_name='transformerdesign',
            name='nucleo',
            field=models.CharField(blank=True, max_length=50, verbose_name='Referencia/Tipo de Núcleo (Opcional)'),
        ),
        migrations.AlterField(
            model_name='transformerdesign',
            name='tipo',
            field=models.CharField(choices=[('monofasico', 'Monofásico'), ('trifasico', 'Trifásico'), ('autotransformador', 'Autotransformador')], max_length=20, verbose_name='Tipo de Sistema'),
        ),
    ]
