# Generated by Django 5.2.12 on 2026-04-04 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kave', '0002_calculotransformador_alto_platina_primario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='calculotransformador',
            name='elevacion_temperatura_c',
            field=models.FloatField(blank=True, null=True, verbose_name='Elevación Térmica (ΔT °C)'),
        ),
        migrations.AddField(
            model_name='calculotransformador',
            name='impedancia_z',
            field=models.FloatField(blank=True, null=True, verbose_name='Impedancia Esperada Z(%)'),
        ),
        migrations.AddField(
            model_name='transformerdesign',
            name='material_bobinas',
            field=models.CharField(choices=[('aluminio', 'Aluminio'), ('cobre', 'Cobre')], default='aluminio', max_length=20, verbose_name='Material de Devanados'),
        ),
        migrations.AlterField(
            model_name='calculotransformador',
            name='peso_cobre_estimado',
            field=models.FloatField(blank=True, null=True, verbose_name='Peso Bobinas (kg)'),
        ),
    ]
