# Generated by Django 5.2.12 on 2026-04-02 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kpis", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Forecast",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[("ventas", "Ventas")], default="ventas", max_length=50
                    ),
                ),
                ("periodo", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=14)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "unique_together": {("tipo", "periodo")},
            },
        ),
    ]
