# Generated by Django 5.2.12 on 2026-04-02 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=80, unique=True)),
                ('tipo', models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta')], default='compra', max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('valor_contrato', models.DecimalField(decimal_places=2, max_digits=14)),
                ('estado', models.CharField(choices=[('negociacion', 'Negociación'), ('activo', 'Activo'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='negociacion', max_length=25)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='compras.proveedor')),
            ],
        ),
    ]
