# Generated by Django 5.2.12 on 2026-04-25 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_pagocompra_recepcioncompra'),
        ('inventarios', '0002_rename_categoriaproducto_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_proveedor', models.CharField(blank=True, help_text='Código del producto según el proveedor', max_length=50)),
                ('precio_proveedor', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tiempo_entrega_dias', models.IntegerField(default=7, help_text='Días de entrega promedio')),
                ('es_proveedor_principal', models.BooleanField(default=False, help_text='Proveedor principal para este producto')),
                ('notas', models.TextField(blank=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='inventarios.producto')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='compras.proveedor')),
            ],
            options={
                'verbose_name': 'Producto por Proveedor',
                'verbose_name_plural': 'Productos por Proveedor',
                'db_table': 'compras_productoproveedor',
                'unique_together': {('producto', 'proveedor')},
            },
        ),
    ]
