# Generated by Django 5.2.12 on 2026-04-29 16:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0004_productoproveedor'),
        ('inventarios', '0004_almacen_alter_movimientoinventario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contrato',
            options={'ordering': ['-fecha_inicio'], 'verbose_name': 'Contrato', 'verbose_name_plural': 'Contratos'},
        ),
        migrations.AlterModelOptions(
            name='detalleordencompra',
            options={'verbose_name': 'Detalle de Orden de Compra', 'verbose_name_plural': 'Detalles de Orden de Compra'},
        ),
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ['-fecha_emision'], 'verbose_name': 'Orden de Compra', 'verbose_name_plural': 'Órdenes de Compra'},
        ),
        migrations.AlterModelOptions(
            name='pagocompra',
            options={'ordering': ['-fecha'], 'verbose_name': 'Pago de Compra', 'verbose_name_plural': 'Pagos de Compra'},
        ),
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['razon_social'], 'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.AlterModelOptions(
            name='recepcioncompra',
            options={'ordering': ['-fecha'], 'verbose_name': 'Recepción de Mercancía', 'verbose_name_plural': 'Recepciones de Mercancía'},
        ),
        migrations.RemoveField(
            model_name='recepcioncompra',
            name='cantidad_recibida',
        ),
        migrations.AddField(
            model_name='contrato',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='compras/contratos/', verbose_name='Archivo del contrato'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='cantidad_recibida',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cantidad recibida acumulada'),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='notas',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='detalleordencompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Subtotal línea'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='condicion_pago',
            field=models.CharField(blank=True, max_length=50, verbose_name='Condición de pago'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='descuento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Descuento'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='iva',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='IVA'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='numero',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Número de OC'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='observaciones',
            field=models.TextField(blank=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='porcentaje_iva',
            field=models.DecimalField(decimal_places=2, default=19, max_digits=5, verbose_name='% IVA'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Subtotal'),
        ),
        migrations.AddField(
            model_name='pagocompra',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pagocompra',
            name='notas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='calificacion',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Evaluación de desempeño del proveedor', max_digits=3, null=True, verbose_name='Calificación (1-5)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='categoria',
            field=models.CharField(choices=[('materias_primas', 'Materias Primas'), ('insumos', 'Insumos / Consumibles'), ('maquinaria', 'Maquinaria y Equipos'), ('servicios', 'Servicios'), ('empaques', 'Empaques'), ('transporte', 'Transporte / Logística'), ('tecnologia', 'Tecnología'), ('otro', 'Otro')], default='materias_primas', max_length=20, verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ciudad',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='condicion_pago',
            field=models.CharField(blank=True, default='Contado', help_text='Ej: Contado, 30 días, 60 días', max_length=50, verbose_name='Condición de pago'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='contacto_telefono_alt',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono alternativo'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='departamento',
            field=models.CharField(blank=True, max_length=100, verbose_name='Departamento'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='descuento_general',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento general (%)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('bloqueado', 'Bloqueado'), ('en_evaluacion', 'En Evaluación')], default='activo', max_length=15, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='moneda',
            field=models.CharField(default='COP', help_text='COP, USD, EUR', max_length=10, verbose_name='Moneda'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre comercial'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas internas'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='sitio_web',
            field=models.URLField(blank=True, verbose_name='Sitio web'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tiempo_entrega_promedio_dias',
            field=models.PositiveIntegerField(default=7, verbose_name='Tiempo de entrega promedio (días)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_documento',
            field=models.CharField(choices=[('NIT', 'NIT'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte')], default='NIT', max_length=5, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='recepcioncompra',
            name='fecha_registro',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recepcioncompra',
            name='numero',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='recepcioncompra',
            name='recibido_por',
            field=models.CharField(blank=True, max_length=100, verbose_name='Recibido por'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='codigo',
            field=models.CharField(max_length=80, unique=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='estado',
            field=models.CharField(choices=[('negociacion', 'Negociación'), ('activo', 'Activo'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='negociacion', max_length=25, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de fin'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='fecha_inicio',
            field=models.DateField(verbose_name='Fecha de inicio'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='compras.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='tipo',
            field=models.CharField(choices=[('compra', 'Compra'), ('venta', 'Venta'), ('suministro', 'Suministro'), ('servicio', 'Prestación de Servicios')], default='compra', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='contrato',
            name='valor_contrato',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Valor del contrato'),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio unitario'),
        ),
        migrations.AlterField(
            model_name='detalleordencompra',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventarios.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='estado',
            field=models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada al Proveedor'), ('confirmada', 'Confirmada por Proveedor'), ('recibida_parcial', 'Recibida Parcialmente'), ('completada', 'Completada'), ('cancelada', 'Cancelada')], default='borrador', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha_emision',
            field=models.DateField(auto_now_add=True, verbose_name='Fecha de emisión'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='fecha_entrega_esperada',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de entrega esperada'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='compras.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='pagocompra',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de pago'),
        ),
        migrations.AlterField(
            model_name='pagocompra',
            name='metodo',
            field=models.CharField(choices=[('transferencia', 'Transferencia Bancaria'), ('efectivo', 'Efectivo'), ('cheque', 'Cheque'), ('tarjeta', 'Tarjeta Corporativa'), ('credito', 'Crédito del Proveedor')], default='transferencia', max_length=20, verbose_name='Método de pago'),
        ),
        migrations.AlterField(
            model_name='pagocompra',
            name='monto',
            field=models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='pagocompra',
            name='referencia',
            field=models.CharField(blank=True, max_length=100, verbose_name='Referencia / Comprobante'),
        ),
        migrations.AlterField(
            model_name='productoproveedor',
            name='precio_proveedor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio del proveedor'),
        ),
        migrations.AlterField(
            model_name='productoproveedor',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proveedores', to='inventarios.producto', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='productoproveedor',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='compras.proveedor', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto_email',
            field=models.EmailField(max_length=254, verbose_name='Email del Contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto_nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre del Contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(max_length=50, unique=True, verbose_name='NIT / Documento'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(max_length=200, verbose_name='Razón Social'),
        ),
        migrations.AlterField(
            model_name='recepcioncompra',
            name='comentario',
            field=models.TextField(blank=True, verbose_name='Comentarios'),
        ),
        migrations.AlterField(
            model_name='recepcioncompra',
            name='fecha',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha de recepción'),
        ),
        migrations.CreateModel(
            name='DetalleRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_recibida', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad recibida')),
                ('cantidad_rechazada', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Cantidad rechazada')),
                ('motivo_rechazo', models.CharField(blank=True, max_length=200, verbose_name='Motivo del rechazo')),
                ('lote', models.CharField(blank=True, max_length=50, verbose_name='Número de lote')),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('detalle_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recepciones_detalle', to='compras.detalleordencompra', verbose_name='Línea de OC')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_recepcion', to='compras.recepcioncompra')),
            ],
            options={
                'verbose_name': 'Detalle de Recepción',
                'verbose_name_plural': 'Detalles de Recepción',
            },
        ),
        migrations.CreateModel(
            name='SolicitudCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=30, unique=True, verbose_name='Número de solicitud')),
                ('solicitante', models.CharField(max_length=100, verbose_name='Solicitante')),
                ('departamento', models.CharField(blank=True, max_length=100, verbose_name='Departamento')),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_requerida', models.DateField(blank=True, null=True, verbose_name='Fecha requerida')),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10, verbose_name='Prioridad')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('convertida', 'Convertida a OC'), ('cancelada', 'Cancelada')], default='pendiente', max_length=15, verbose_name='Estado')),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('mrp', 'MRP'), ('produccion', 'Producción'), ('mantenimiento', 'Mantenimiento'), ('almacen', 'Almacén (Stock Bajo)')], default='manual', max_length=15, verbose_name='Origen')),
                ('justificacion', models.TextField(blank=True, verbose_name='Justificación')),
                ('aprobado_por', models.CharField(blank=True, max_length=100, verbose_name='Aprobado por')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('orden_compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solicitudes', to='compras.ordencompra', verbose_name='Orden de Compra generada')),
            ],
            options={
                'verbose_name': 'Solicitud de Compra',
                'verbose_name_plural': 'Solicitudes de Compra',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='DetalleSolicitudCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Cantidad solicitada')),
                ('cantidad_aprobada', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Cantidad aprobada')),
                ('notas', models.CharField(blank=True, max_length=200)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventarios.producto', verbose_name='Producto')),
                ('proveedor_sugerido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='compras.proveedor', verbose_name='Proveedor sugerido')),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='compras.solicitudcompra', verbose_name='Solicitud')),
            ],
            options={
                'verbose_name': 'Detalle de Solicitud',
                'verbose_name_plural': 'Detalles de Solicitud',
            },
        ),
    ]
