# Generated by Django 5.2.12 on 2026-05-17 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0005_alter_contrato_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='actividad_economica_ciiu',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Actividad Económica (CIIU)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='agente_retenedor',
            field=models.BooleanField(default=False, verbose_name='¿Agente Retenedor?'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='codigo_barras',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código de Barras'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='correo_facturacion_electronica',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo para Facturación Electrónica'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='digito_verificacion',
            field=models.CharField(blank=True, max_length=1, null=True, verbose_name='Dígito Verificación'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_resolucion_dian',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Resolución DIAN'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='gran_contribuyente',
            field=models.BooleanField(default=False, verbose_name='¿Gran Contribuyente?'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='matricula_mercantil',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Matrícula Mercantil'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='numero_resolucion_dian',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Resolución DIAN'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='regimen_tributario',
            field=models.CharField(choices=[('comun', 'Régimen Común'), ('simplificado', 'Régimen Simplificado'), ('especial', 'Régimen Especial')], default='comun', max_length=20, verbose_name='Régimen Tributario'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='responsabilidades_fiscales',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Responsabilidades Fiscales (DIAN)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='responsable_iva',
            field=models.BooleanField(default=False, verbose_name='¿Responsable de IVA?'),
        ),
    ]
