# Generated by Django 5.2.12 on 2026-06-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0006_proveedor_actividad_economica_ciiu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='adjunto_archivos',
            field=models.FileField(blank=True, null=True, upload_to='compras/adjuntos/', verbose_name='Adjuntos'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='banco_nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Banco'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cargo_contacto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cargo Contacto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cedula_representante',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Cédula Representante'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ciudad_entrega',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ciudad Entrega'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='clasificacion',
            field=models.CharField(blank=True, choices=[('A', 'Clase A - Premium'), ('B', 'Clase B - Estándar'), ('C', 'Clase C - Básico')], default='B', max_length=1, verbose_name='Clasificación'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='codigo_bancario',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Bancario'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='codigo_postal',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Código Postal'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='codigo_proveedor',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Código Proveedor'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='credito_maximo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='Crédito Máximo (COP)'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='dias_credito',
            field=models.PositiveIntegerField(default=0, verbose_name='Días de Crédito'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='direccion_entrega',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección de Entrega'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email Principal'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fax',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fax'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_constitucion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Constitución'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='fecha_ultimo_contacto',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Último Contacto'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='lista_precios',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lista de Precios'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='logotipo',
            field=models.ImageField(blank=True, null=True, upload_to='compras/logotipos/', verbose_name='Logotipo'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='numero_cuenta',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Número de Cuenta'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='pais',
            field=models.CharField(blank=True, default='Colombia', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='representante_legal',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Representante Legal'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='sector_industria',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sector / Industria'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono Principal'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='telefono_alterno',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono Alterno'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_cuenta',
            field=models.CharField(blank=True, choices=[('corriente', 'Cuenta Corriente'), ('ahorros', 'Cuenta de Ahorros'), ('nomina', 'Cuenta Nómina')], max_length=20, null=True, verbose_name='Tipo de Cuenta'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='tipo_proveedor',
            field=models.CharField(blank=True, choices=[('persona_natural', 'Persona Natural'), ('empresa', 'Empresa'), ('empresa_unipersonal', 'Empresa Unipersonal'), ('cooperativa', 'Cooperativa')], default='empresa', max_length=25, verbose_name='Tipo de Proveedor'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='titular_cuenta',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Titular Cuenta'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='condicion_pago',
            field=models.CharField(blank=True, default='Contado', help_text='Ej: Contado, 30 días, 60 días', max_length=50, verbose_name='Condición de Pago'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email del Contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto_nombre',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del Contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto_telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono Contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='contacto_telefono_alt',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono Alternativo Contacto'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='descuento_general',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Descuento General (%)'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='direccion',
            field=models.TextField(blank=True, verbose_name='Dirección de Facturación'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='moneda',
            field=models.CharField(default='COP', max_length=10, verbose_name='Moneda'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='nombre_comercial',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nombre Comercial'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='notas',
            field=models.TextField(blank=True, verbose_name='Notas Internas'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='sitio_web',
            field=models.URLField(blank=True, verbose_name='Sitio Web'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tiempo_entrega_promedio_dias',
            field=models.PositiveIntegerField(default=7, verbose_name='Tiempo de Entrega Promedio (días)'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='tipo_documento',
            field=models.CharField(choices=[('NIT', 'NIT'), ('CC', 'Cédula de Ciudadanía'), ('CE', 'Cédula de Extranjería'), ('PAS', 'Pasaporte')], default='NIT', max_length=5, verbose_name='Tipo de Documento'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['nit'], name='compras_pro_nit_71fcb9_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['codigo_proveedor'], name='compras_pro_codigo__54e572_idx'),
        ),
        migrations.AddIndex(
            model_name='proveedor',
            index=models.Index(fields=['estado'], name='compras_pro_estado_ad670c_idx'),
        ),
    ]
