# Generated by Django 5.2.12 on 2026-06-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0007_proveedor_adjunto_archivos_proveedor_banco_nombre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='nit',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='NIT / Documento'),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='razon_social',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Razón Social'),
        ),
    ]
