# Generated by Django 5.2.12 on 2026-04-02 20:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nit', models.CharField(max_length=20, unique=True, verbose_name='NIT')),
                ('razon_social', models.CharField(max_length=200, verbose_name='Razón Social')),
                ('nombre_comercial', models.CharField(blank=True, max_length=200, verbose_name='Nombre Comercial')),
                ('tipo_empresa', models.CharField(choices=[('matriz', 'Matriz'), ('sucursal', 'Sucursal'), ('filial', 'Filial'), ('independiente', 'Independiente')], default='independiente', max_length=50)),
                ('regimen_fiscal', models.CharField(choices=[('comun', 'Régimen Común'), ('simplificado', 'Régimen Simplificado'), ('especial', 'Régimen Especial')], default='comun', max_length=50)),
                ('tipo_contribuyente', models.CharField(choices=[('persona_natural', 'Persona Natural'), ('persona_juridica', 'Persona Jurídica')], default='persona_juridica', max_length=50)),
                ('direccion', models.TextField(blank=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('sitio_web', models.URLField(blank=True)),
                ('moneda_base', models.CharField(default='COP', max_length=3)),
                ('pais', models.CharField(default='Colombia', max_length=50)),
                ('ciudad', models.CharField(blank=True, max_length=50)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_modificacion', models.DateTimeField(auto_now=True)),
                ('administrador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresas_administradas', to=settings.AUTH_USER_MODEL, verbose_name='Administrador')),
                ('empresa_matriz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sucursales', to='multi_empresa.empresa', verbose_name='Empresa Matriz')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año_fiscal_inicio', models.IntegerField(default=1)),
                ('moneda_reportes', models.CharField(default='COP', max_length=3)),
                ('formato_fecha', models.CharField(default='DD/MM/YYYY', max_length=20)),
                ('metodo_valuacion_inventario', models.CharField(choices=[('fifo', 'FIFO'), ('lifo', 'LIFO'), ('promedio_ponderado', 'Promedio Ponderado'), ('identificacion_especifica', 'Identificación Específica')], default='promedio_ponderado', max_length=50)),
                ('porcentaje_iva_default', models.DecimalField(decimal_places=2, default=19.0, max_digits=5)),
                ('porcentaje_retefuente_default', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('porcentaje_reteica_default', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('digitos_cuenta_contable', models.IntegerField(default=8)),
                ('permite_asientos_automaticos', models.BooleanField(default=True)),
                ('requiere_aprobacion_compras', models.BooleanField(default=True)),
                ('monto_minimo_aprobacion', models.DecimalField(decimal_places=2, default=1000000, max_digits=14)),
                ('empresa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion', to='multi_empresa.empresa')),
            ],
            options={
                'verbose_name': 'Configuración de Empresa',
                'verbose_name_plural': 'Configuraciones de Empresa',
            },
        ),
        migrations.CreateModel(
            name='CentroCosto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.TextField(blank=True)),
                ('tipo_centro', models.CharField(choices=[('produccion', 'Producción'), ('administrativo', 'Administrativo'), ('ventas', 'Ventas'), ('distribucion', 'Distribución'), ('servicio', 'Servicio')], default='administrativo', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='centros_costo', to='multi_empresa.empresa')),
            ],
            options={
                'verbose_name': 'Centro de Costo',
                'verbose_name_plural': 'Centros de Costo',
                'ordering': ['empresa', 'codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, verbose_name='Código Almacén')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('direccion', models.TextField(blank=True)),
                ('ciudad', models.CharField(blank=True, max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('tipo_almacen', models.CharField(choices=[('principal', 'Principal'), ('secundario', 'Secundario'), ('transito', 'Tránsito'), ('devoluciones', 'Devoluciones'), ('consignacion', 'Consignación')], default='principal', max_length=50)),
                ('activo', models.BooleanField(default=True)),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='almacenes', to='multi_empresa.empresa')),
            ],
            options={
                'verbose_name': 'Almacén',
                'verbose_name_plural': 'Almacenes',
                'ordering': ['empresa', 'codigo'],
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='UsuarioEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol_empresa', models.CharField(choices=[('administrador', 'Administrador'), ('gerente', 'Gerente'), ('supervisor', 'Supervisor'), ('operador', 'Operador'), ('consultor', 'Consultor')], default='operador', max_length=50)),
                ('permisos_especificos', models.JSONField(blank=True, default=dict, help_text='Permisos específicos por módulo')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_asignacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_asignados', to='multi_empresa.empresa')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Empresa',
                'verbose_name_plural': 'Usuarios Empresa',
                'ordering': ['empresa', 'rol_empresa', 'usuario'],
                'unique_together': {('usuario', 'empresa')},
            },
        ),
    ]
