# Generated by Django 5.2.12 on 2026-06-19 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multi_empresa', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='almacenes_multi_empresa', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='centrocosto',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='centros_costo_multi_empresa', to=settings.AUTH_USER_MODEL),
        ),
    ]
